### ISSUE TITLE
Method Geometry#intersection not defined.

### ISSUE THREAD

**Issue by Pistorius** [rgeo/rgeo#101]
I'm on OS X, 64 bits architecture. i've installed rgeo.

```
irb(main):002:0> RGeo::Geos.supported?
=> true
```

But when i try something like this `@geom.intersection(union_geom)`, I get the error
```
Method Geometry#intersection not defined.
```

**Comment by pankas87** [comment]
I had the same problem in Ubuntu.

Try on of these two things

Completely uninstall RGeo Gem and install it again to see if it gets correctly linked to GEOS.

if that fails try:

-Uninstall RGeo Gem
-Find the location in your system of the GEOS packages. In ubuntu you can find it in /usr/lib
-If the GEOS package has a name different from libgeos.so, like may be libegos-3.4.2.so create a symbolic link name libgeos.so, pointing to your local version of the GEOS package.

sudo ln -s /usr/lib/libgeos-3.4.2 /usr/lib/libgeos.so

-Reinstall RGeo

Hope it helps

**Comment by Pistorius** [comment]
Trying to solve it with the second option u gave to me I'm not sure but it seem like there are not a `.so` file. I found the location of `geos` in `/usr/local/Cellar/geos/3.4.2`.

**Comment by Pistorius** [comment]
I created the symbolic link of my libgeos-3.4.2.dylib (a .dylib because im on osx) with
```
sudo ln -s libgeos-3.4.2.dylib /usr/lib/libgeos.dylib
```
And after reinstall rgeo but I still get the same error :/

**Comment by pankas87** [comment]
Is this a rails project?

If so, run

    bundle exec run rails c

    RGeo::Geos.supported?

That command outputs true or false?

**Comment by Pistorius** [comment]
```
rails c
Loading development environment (Rails 4.0.0)
irb(main):001:0> RGeo::Geos.supported?
=> true
```

**Comment by pankas87** [comment]
http://www.rubydoc.info/github/dazuma/rgeo/RGeo/Feature/Geometry:intersection

What are the class names of the objects you're trying to intersect? Are they created by the same Factory?

**Comment by Pistorius** [comment]
The first object:
```
RGeo::Geographic::SphericalPolygonImpl:0x815d6390 "POLYGON ((-70.53445816040039 ...
```
the second:

```
RGeo::Geos::CAPIPolygonImpl:0x80d897a0 "POLYGON ((-70.47723513299997 ...
```

**Comment by pankas87** [comment]
From the docs:

"Although implementations are free to attempt to handle another_geometry values that do not share the same factory as this geometry, strictly speaking, the result of performing operations on objects from different factories is undefined."

http://www.rubydoc.info/github/dazuma/rgeo/RGeo/Feature/Geometry:intersection

**Comment by Pistorius** [comment]
Bingo! Thanks a lot!
