### ISSUE TITLE
Method missing: undefined method `rgeo_factory_generator='

### ISSUE THREAD

**Issue by phlegx** [rgeo/rgeo#103]
Hi!

If I run my application in production mode I get this error:

```log
/activerecord-4.2.2/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `rgeo_factory_generator=' for #<Class:0x000000071b99
f8> (NoMethodError)
```

The error is on line 2:

```ruby
class Address < ActiveRecord::Base
  self.rgeo_factory_generator = RGeo::Geos.factory_generator(srid: 4326)
  set_rgeo_factory_for_column :coordinates, RGeo::Geographic.spherical_factory(srid: 4326)
...
```

On development mode all works fine. I use rgeo v0.3.20 and rgeo-activerecord v4.0.0 and rails 4.2.2! Any idea?

### EDIT

If I set ```config.eager_load``` in production environment to false, all works fine! Why?

**Comment by teeparham** [comment]
`rgeo_factory_generator` was removed from `rgeo-activerecord` in version 4.0.

See https://github.com/rgeo/rgeo-activerecord/commit/b1da5cb22248

I updated the readme here:

https://github.com/rgeo/rgeo-activerecord/blob/master/README.md#factory-generator-changes
