### ISSUE TITLE
Maintainer is inactive, let's maintain it together !

### ISSUE THREAD

**Issue by guizmaii** [rgeo/rgeo#106]
Hi everyone interessed in this gem,

I'm very upset by this gem.

1. The doc is not understable. We have to read and understand the code to make something with this gem.
2. The code is bugged !
3. When bugs happens, it returns nil instead of fail.
4. There's no response of the maintainers team for issues nor pull resquests.

It does not respect the OSS philosophy at all !
I'm not happy at all !

So, I forked this repo here : https://github.com/oegr/rgeo
I created a Gitter channel here : (I'll create it as soon as Gitter recognize my new **oegr** organization)

Every one is welcome for PRs.
I created a Github organization to federate the new maintainers team, if anyone is interested to join, ask me ;)

I haven't a lot of time to maintain it. I'm pretty new to this "geospatial subject". I don't understand, for now, a lot of things about this code. I'm not a ninja in Ruby. And my english is not perfect.
But it can't be worst than here.

So, let's improve this gem ! Ruby need a great gem for this kind of computations.

Jules

**Comment by dazuma** [comment]
@guizmaii Could I interest you in just taking over maintainership of this original repository rather than causing confusion with a fork?

**Comment by teeparham** [comment]
@dazuma I'd like to see a few useful PR's/contributions before handing over the reins just yet.

**Comment by eddietejeda** [comment]
I would like to see contributions by @guizmaii before any change in control. I depend heavily on rgeo and I don't want cowboy releases that break things unnecessarily.

**Comment by pankas87** [comment]
+1 @eddietejeda 

A handful of projects on my company depend on RGeo.

Also, I don't think that gem is bugy or that it has hard to understand documentation, I think it is quite the opposite. RGeo docs and tutorials are great and the gem is very stable if you set-up well your environment (Geos and Proj dependencies mainly)

**Comment by doomspork** [comment]
+1 to waiting for contributions.  We rely pretty heavily on this gem.

**Comment by teeparham** [comment]
I released 0.4.0 today.

Again, I welcome contributions from anyone who can make this project better. If you'd like to help, you can submit issues, review issues, test existing PRs, and submit your own PRs.

If anyone makes significant contributions and knows what they're doing, I will be happy to add them to the rgeo organization & give them access to this project.

Closing this issue.
