### ISSUE TITLE
Heroku and ruby 2.3

### ISSUE THREAD

**Issue by steffenix** [rgeo/rgeo#129]
Seems Not possible to use 0.5.2 with ruby 2.3
Getting 
`remote:        sh: 1: Syntax error: Unterminated quoted string`
`remote:        Gem::Ext::BuildError: ERROR: Failed to build gem native extension.`
`remote:        current directory: /tmp/build_f0f6bced89dbe3703a655305b819c9c2/vendor/bundle/ruby/2.3.0/gems/rgeo-0.5.2/ext/geos_c_impl`
`remote:        /tmp/build_f0f6bced89dbe3703a655305b819c9c2/vendor/ruby-2.3.0/bin/ruby -r ./siteconf20151228-341-jcvy64.rb extconf.rb '''''''''''''''''''--with-geos-dir=/tmp/build_82325631c96ff891169659463f7dfe7f/.heroku/vendor --with-geos-lib=/tmp/build_82325631c96ff891169659463f7dfe7f/.heroku/vendor/lib --with-proj-dir=/tmp/build_82325631c96ff891169659463f7dfe7f/.heroku/vendor''''''''''''''''''`

**Comment by steffenix** [comment]
FYI use `heroku repo:purge_cache` and push again

**Comment by ivar** [comment]
@steffenix Thanks for posting this.. I just ran into it and your solution worked for me.
