### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tilo** [rgeo/rgeo#130]
Can you make this available under the MIT license?

**Comment by teeparham** [comment]
I would be OK with changing the license to MIT for all the rgeo gems. @dazuma wrote the original rgeo family of gems, so he would need to agree to the change.

FWIW, there is not much difference between BSD and MIT: http://choosealicense.com/licenses/

Is there anything you would do differently with an MIT license?

**Comment by dazuma** [comment]
I'm not fundamentally opposed to changing the license, although I preferred the "new-style" BSD license because of the trademark clause. @tilo is there a particular reason you need MIT over BSD?

**Comment by veganstraightedge** [comment]
Bump.

https://github.com/rgeo/rgeo-activerecord/issues/58

Is this still possible to do, please? To either BSD or MIT?

**Comment by keithdoggett** [comment]
It looks like all of the gems but  rgeo/proj4 are already under BSD license, so I can go through later today and update the gemspecs.

I'm going to leave the licenses as BSD since as Tee pointed out, there's essentially no difference and there hasn't been a compelling reason to change to MIT presented.

**Comment by veganstraightedge** [comment]
Thank you @keithdoggett! 🎉
I super appreciate it.

**Comment by keithdoggett** [comment]
This has fixed done across the ecosystem so that all the gems have an OSI license compatible name in the `.gemspec`.

**Comment by veganstraightedge** [comment]
Thank you!

Will there be a patch release of the gem to publish this change into the wild?
