### ISSUE TITLE
Rename variables ending with _

### ISSUE THREAD

**Issue by teeparham** [rgeo/rgeo#133]
Let's name arguments and local variables without a trailing `_`

Now:

``` ruby
def sum(x_, y_)
  x_ + y_
end
```

Better:

``` ruby
def sum(x, y)
  x + y
end
```

**Comment by zacscodingclub** [comment]
Hi @teeparham
I'm transitioning from a GIS analyst to Ruby developer and want to help out in OSS.  This issue seems to be something where I can make a contribution without needing to understand all the deeper moving parts of the rest of the library.

Is this a project you're still hoping to see completed?

**Comment by teeparham** [comment]
Yes, this would still be great to do. And it doesn't need to all be done at once. One file at a time would work.

**Comment by fergyfresh** [comment]
This still something we wanna do? I started working on it on a fork and I think I can batch update it with regex and verify all the tests still pass tonight. Pretty much everything is either "_ ", "_." or "_)". The only question I have is do we want to keep `_variables_like_this_` untouched or make them `_variables_like_that`.

**Comment by teeparham** [comment]
Thanks for working on this. I would remove preceding `_`s too, if possible. 

✅ `variables_like_this`

**Comment by fergyfresh** [comment]
Unrelated, how in the world do you make that cool checkmark?

**Comment by fergyfresh** [comment]
A decent amount of test code is gonna have to change too. Is that cool?

**Comment by teeparham** [comment]
Yes - that's great to update the test code too. 

(the ✅ is just emoji - here's a list of all https://gist.github.com/rxaviers/7360908)

**Comment by fergyfresh** [comment]
Last question on the docket, `def _generator_blah` to `def generator_blah` or no?

**Comment by teeparham** [comment]
Please do the method renames in a separate pull request. Renaming methods are breaking changes unless they are private methods. Breaking changes are ok since there are already a lot in master, & we're headed for a 2.0 release.

**Comment by fergyfresh** [comment]
I'll see what I can manage. Both PRs to master? Or do we want the variable one to something else?

**Comment by teeparham** [comment]
PRs to master. It sounds like you may want to do the variable renames first, & then the method renames off that branch. That's fine & we can rebase if so.

**Comment by fergyfresh** [comment]
Finally finished #181.
