### ISSUE TITLE
jruby proj4 support

### ISSUE THREAD

**Issue by odix67** [rgeo/rgeo#135]
Is there any reason to not support Proj4 with jruby, as there exists a [ffi-proj4](https://github.com/dark-panda/ffi-proj4) gem ?

kind regards
odi

**Comment by teeparham** [comment]
That would be a great contribution.

Proj4 has been extracted to a separate gem, `rgeo-proj4`. Please re-open this issue in https://github.com/rgeo/rgeo-proj4 if it is still a problem. Thanks.
