### ISSUE TITLE
Slow performance with RGeo::WKRep::WKBParser#parse

### ISSUE THREAD

**Issue by pedros007** [rgeo/rgeo#139]
I have a multipolygon of Australia ([viewable map](https://bl.ocks.org/anonymous/raw/420fd0e7ef82131c54bb/) and [2.2 MB geojson](https://bl.ocks.org/anonymous/raw/420fd0e7ef82131c54bb/map.geojson) and [6.2 MB wkb](https://gist.github.com/pedros007/51666e6eb82d3a3576de).  The performance of `RGeo::WKRep::WKBParser#parse` is surprisingly slow: it takes almost 9 minutes to return the RGeo Geometry

```
puts Benchmark.measure { RGeo::WKRep::WKBParser.new( ).parse(File.read('australia5.wkb'));0 }
532.330000   6.270000 538.600000 (553.606447)
```

For comparison, parsing the WKB into GeoJSON directly via postgis takes 1 ms via `select ST_AsGeoJSON(geom) from aois where id=74;`.  I did not expect RGeo to be 6 orders of magnitude slower.  Does anyone know what is going on?

Ultimately this is in a Postgis table accessed via activerecord-postgis-adapter (schema is `create_table :aois { |t| t.geometry :geom, srid: 4326 }`. When I access the `geom` column, [ruby-prof](https://github.com/ruby-prof/ruby-prof) shows 99% of the total time is spent in `RGeo::WKRep::WKBParser#parse` and further down the stack `<Class::RGeo::Geos::CAPIMultiPolygonImpl>#create`.

I'm using ruby-2.2.3p173, `RGeo::Geos.supported?` returns true.  For comparison, I'm running Postgres-9.4.4 and Postgis  2.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

Here Rgeo versions from my Gemfile.lock:

```
activerecord-postgis-adapter (3.1.4)
  activerecord (~> 4.2)
  rgeo-activerecord (>= 4.0.4)
rgeo (0.4.0)
rgeo-activerecord (4.0.5)
  activerecord (~> 4.2)
  rgeo (~> 0.3)
rgeo-geojson (0.3.1)
  rgeo (~> 0.3)
```

This may be related to #116.

**Comment by pedros007** [comment]
Looks like PR #119 may help.  It is only in rgeo >= 0.5.0.  Let me test with that version and get back.

**Comment by pedros007** [comment]
rgeo-0.5.3 is much faster than 0.4.0 (Thanks, @tneems for #119!), but `RGeo::WKRep::WKBParser#parse` is still slower than I expected:

    puts Benchmark.measure { RGeo::WKRep::WKBParser.new( ).parse(File.read('australia5.wkb'));0 }
    292.880000   3.370000 296.250000 (305.606821)

**Comment by tneems** [comment]
@pedros007 I've been working on some patches for [RGeo](https://github.com/tneems/rgeo/tree/hex-in-c) and the [postgis adapter](https://github.com/tneems/activerecord-postgis-adapter/tree/fast-wkb) that speed up the WKB parsing when dealing with a postgis while using a geos backed factory. You could also use this with plain rgeo by calling `factory.parse_wkb(wkb_string)`. I've been using these changes with EWKB YMMV with plain WKB.

Here is an idea of the type of speed improvements I experienced with these branches that I've been running in production for about a week.

```ruby
Benchmark.ips do |x|
  x.report("geos parse") do
    factory.parse_wkb point
  end

  x.report("rgeo ruby parse") do
    RGeo::WKRep::WKBParser.new(factory, support_ewkb: true).parse(point)
  end
end;""
# Calculating -------------------------------------
#           geos parse     8.005k i/100ms
#      rgeo ruby parse     3.906k i/100ms
# -------------------------------------------------
#           geos parse    140.847k (±10.8%) i/s -    664.415k
#      rgeo ruby parse     59.418k (±20.8%) i/s -    273.420k

Benchmark.ips do |x|
  x.report("geos parse") do
    factory.parse_wkb normal_poly
  end

  x.report("rgeo ruby parse") do
    RGeo::WKRep::WKBParser.new(factory, support_ewkb: true).parse(normal_poly)
  end
end;""
# Calculating -------------------------------------
#           geos parse   425.000  i/100ms
#      rgeo ruby parse   103.000  i/100ms
# -------------------------------------------------
#           geos parse      4.311k (± 3.5%) i/s -     21.675k
#      rgeo ruby parse      1.098k (±19.3%) i/s -      4.944k

Benchmark.ips do |x|
  x.report("geos parse") do
    factory.parse_wkb large_poly
  end

  x.report("rgeo ruby parse") do
    RGeo::WKRep::WKBParser.new(factory, support_ewkb: true).parse(large_poly)
  end
end;""
# Calculating -------------------------------------
#           geos parse     1.000  i/100ms
#      rgeo ruby parse     1.000  i/100ms
# -------------------------------------------------
#           geos parse      1.598  (± 0.0%) i/s -      9.000  in   5.631957s
#      rgeo ruby parse      0.247  (± 0.0%) i/s -      2.000  in   8.131894s

Benchmark.ips do |x|
  x.report("geos parse") do
    factory.parse_wkb problem_poly
  end

  x.report("rgeo ruby parse") do
    RGeo::WKRep::WKBParser.new(factory, support_ewkb: true).parse(problem_poly)
  end
end;""
# Calculating -------------------------------------
#           geos parse     3.000  i/100ms
#      rgeo ruby parse     1.000  i/100ms
# -------------------------------------------------
#           geos parse     38.702  (± 5.2%) i/s -    195.000
#      rgeo ruby parse      0.080  (± 0.0%) i/s -      1.000  in  12.535465s
```

**Comment by pedros007** [comment]
@tneems GEOS parsing looks much faster. Do you plan on submitting a PR to RGeo?

**Comment by BuonOmo** [comment]
The PR is very old, but I'm glad to announce that this issue is now fixed by https://github.com/rgeo/rgeo/pull/331
