### ISSUE TITLE
Question: WKT to PROJ4

### ISSUE THREAD

**Issue by emirpasic** [rgeo/rgeo#145]
Tried browsing through code, but couldn't find my answer. 

Trying to accomplish a similar result to running: gdalsrsifno -V -o proj4 some.prj

How would I parse WKT format and create a proj4 string out of it:

http://www.rubydoc.info/gems/rgeo/RGeo/CoordSys/CS/WKTParser

Basically the encode method, but how?

Thanks

**Comment by teeparham** [comment]
Proj4 has been extracted to a separate gem, `rgeo-proj4`. Please re-open this issue in https://github.com/rgeo/rgeo-proj4 if it is still a problem. Thanks.
