### ISSUE TITLE
Polygon intersection methods giving bad results

### ISSUE THREAD

**Issue by ykessler** [rgeo/rgeo#157]
Running into a number of issues with polygon intersection methods (rgeo 0.5.3)

## EXAMPLE 1

Here are two polygons which share a boundary but do not share any internal space (i.e. they touch but do not overlap):

    wkt_1 = "POLYGON ((-8226874.27782158 4962626.76394919, -8223358.174520462 4961756.817075645, -8223358.174520462 4960289.557693501, -8224471.369428394 4960289.557693501, -8226874.27782158 4962253.674727506, -8226874.27782158 4962626.76394919))"
    wkt_2 = "POLYGON ((-8224757.546680832 4960523.476563589, -8225269.1002275925 4959296.105368667, -8226993.791361805 4959219.668340384, -8226420.900079966 4961883.087589158, -8224757.546680832 4960523.476563589))"
    poly_1 = RGeo::Geos.factory(:srid => 3857).parse_wkt(wkt_1)
    poly_2 = RGeo::Geos.factory(:srid => 3857).parse_wkt(wkt_2)

This is confirmed when we check the intersection between them, which returns a line:

    poly_1.intersection poly_2
    => #<RGeo::Geos::CAPILineStringImpl:0x3fc0249af168 "LINESTRING (-8224757.546680832 4960523.476563589, -8225598.074380083 4961210.51680879)">

However, when running the following checks, we get the opposite of what's expected:

    poly_1.overlaps? poly_2
    => true
    poly_1.touches? poly_2
    => false

## EXAMPLE 2

Next, we take two legitimately overlapping polygons:

    wkt_3 = "POLYGON ((-8243236.659872404 4970203.108701159, -8243236.659872404 4968734.582337743, -8242123.464964474 4968734.582337743, -8242123.464964474 4970203.108701159, -8243236.659872404 4970203.108701159))"
    wkt_4 = "POLYGON ((-8244765.4004381085 4966075.509173758, -8244765.4004381085 4964607.602290147, -8243652.205530177 4964607.602290147, -8243652.205530177 4966075.509173758, -8242680.062418439 4969362.301390027, -8244765.4004381085 4966075.509173758))"
    poly_3 = RGeo::Geos.factory(:srid => 3857).parse_wkt(wkt_3)
    poly_4 = RGeo::Geos.factory(:srid => 3857).parse_wkt(wkt_4)

[![enter image description here][3]][3]

And calculate the differences in both directions:

    diff_a = poly_3.difference poly_4
    => #<RGeo::Geos::CAPIPolygonImpl:0x3fd108514424 "POLYGON ((-8243078.32501591 4968734.582337743, -8243236.659872404 4968734.582337743, -8243236.659872404 4970203.108701159, -8242123.464964474 4970203.108701159, -8242123.464964474 4968734.582337743, -8242865.724520766 4968734.582337743, -8242680.062418439 4969362.301390027, -8243078.32501591 4968734.582337743))">
    diff_b = poly_4.difference poly_3
    => #<RGeo::Geos::CAPIPolygonImpl:0x3fd10850d444 "POLYGON ((-8242865.724520766 4968734.582337743, -8243652.205530177 4966075.509173758, -8243652.205530177 4964607.602290147, -8244765.4004381085 4964607.602290147, -8244765.4004381085 4966075.509173758, -8243078.32501591 4968734.582337743, -8242865.724520766 4968734.582337743))">

Now we check the remainder polygons against their subtractors:

    diff_b.touches? poly_3
    => true
    diff_b.overlaps? poly_3
    => false

This is good.

    diff_a.touches? poly_4
    => false
    diff_a.overlaps? poly_4
    => true

This is impossible- There's no way the remainder of a polygon subtracted from another should be able to overlap that polygon!

And how is it only happening in one direction?

## EXAMPLE 3

The weirdness continues. Let's now get the intersection of poly_3 and poly_4

    intersection_a = poly_3.intersection poly_4
    => #<RGeo::Geos::CAPIPolygonImpl:0x3fd1084ece88 "POLYGON ((-8242865.724520766 4968734.582337743, -8243078.32501591 4968734.582337743, -8242680.062418439 4969362.301390027, -8242865.724520766 4968734.582337743))">

Now since this is what should have been subtracted from poly_3 to give us diff_a, diff_a should therefore intersect with intersection_a in exactly the same way as that it intersects with poly_4 (the subtractor). 

Except it doesn't:

    diff_a.touches? poly_4
    => false
    diff_a.touches? intersection_a
    => true
    diff_a.intersection poly_4
    => #<RGeo::Geos::CAPILineStringImpl:0x3fd1075ebd6c "LINESTRING (-8242680.062418439 4969362.301390027, -8243078.32501591 4968734.582337743)">
    diff_a.intersection intersection_a
    => #<RGeo::Geos::CAPIMultiLineStringImpl:0x3fd1084b1be4 "MULTILINESTRING ((-8242865.724520766 4968734.582337743, -8242680.062418439 4969362.301390027), (-8242680.062418439 4969362.301390027, -8243078.32501591 4968734.582337743))">

Worse, neither of those two intersection results make sense. It should be a single, 2-segmented line, which neither of those are.

  [3]: https://i.stack.imgur.com/6x9xx.png

**Comment by teeparham** [comment]
Can you open a pull request & start with some failing tests?

**Comment by keithdoggett** [comment]
I wrote tests that I believe recreate the problems described here (https://github.com/rgeo/rgeo/commit/715ae8db8f55039a8edb9a79486d72c50101d95a) and all the tests passed on libgeos versions 3.5+ so I'm going to close this issue.

If my tests don't properly recreate the issue or if you still see it, feel free to re-open this.
