### ISSUE TITLE
Building RGeo on windows with proj4 support? 

### ISSUE THREAD

**Issue by nathanvda** [rgeo/rgeo#166]
My development machine is a MacBook pro, and generally I deploy on linux machines and then using this library is smoooooth sailing. But one client wants me to deploy on their inhouse windows server. This is in general not a problem, except when trying to do coordinate transformations using `rgeo`.

I was able to get GEOS support by 

* installing `ffi-geos` gem
* setting the environment-variable `GEOS_LIBRARY_PATH` to the path where the dll is located (in my case `c:\osgeo4w\bin`)
* then `RGeo::Geos::supported?` returns `true`! :smile: 

(I was under the wrongful impression if I had geos support, proj4 would automatically be fixed as well, ooops)

But, when trying to achieve the same for proj4 has proven not to be so easy. I keep getting `RGeo::CoordSys::Proj4.supported?` to be false. 

I tried to do `gem install rgeo -- --with-proj-dir="c:/osgeo4w"` and it failed. So I added the `--verbose` flag to see a little more, and then I got the following: 

```
Building native extensions with: '--with-proj-dir=c:/osgeo4w --verbose'
This could take a while...
c:/Ruby21/bin/ruby.exe extconf.rb --with-proj-dir=c:/osgeo4w --verbose
checking for geos-config... no
checking for geos_c.h... no
**** WARNING: Unable to find GEOS headers or libraries.
**** Ensure that 'geos-config' is in your PATH or provide that full path via --with-geos-config
**** Compiling without GEOS support.
make "DESTDIR=" clean
make: *** No rule to make target `clean'.  Stop.
make "DESTDIR="
make: Nothing to be done for `install'.
make "DESTDIR=" install
make: Nothing to be done for `install'.
Building has failed. See above output for more information on the failure.
c:/Ruby21/bin/ruby.exe extconf.rb --with-proj-dir=c:/osgeo4w --verbose
checking for proj_api.h... yes
checking for pj_init_plus() in proj_api.h... no
**** WARNING: Unable to find Proj headers or Proj version is too old.
**** Compiling without Proj support.
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
generating proj4_c_impl-i386-mingw32.def
compiling main.c
linking shared-object rgeo/coord_sys/proj4_c_impl.so
make "DESTDIR=" install
/usr/bin/install -c -m 0755 proj4_c_impl.so ./.gem.20170201-5656-19bm06q/rgeo/coord_sys
installing default proj4_c_impl libraries

Successfully installed rgeo-0.5.3
Parsing documentation for rgeo-0.5.3
Parsing sources...
100% [80/80]  lib/rgeo/yaml.rb
Done installing documentation for rgeo after 3 seconds
1 gem installed
```

So it does find the `proj_api.h` but it does not find the function `pj_init_plus` inside that file (while I verified manually it definitely is there).

So checking the [code](https://github.com/rgeo/rgeo/blob/master/ext/proj4_c_impl/extconf.rb#L50), I have the impression the `have_func` might not work on windows, or am I overlooking something really obvious? 

So my question is: is there a way to get proj4 working on windows, or what should I do/try to make it working? 

For completeness, I am using 

* ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
* gem 2.2.3

**Comment by geolibrerian** [comment]
Any luck on this issue?

**Comment by nathanvda** [comment]
Nope, no progress. I switched to using postgis for my coordinate transformations (on windows). Any tips?

**Comment by teeparham** [comment]
Proj4 has been extracted to a separate gem, `rgeo-proj4`. Please try the latest version of rgeo & re-open this issue in https://github.com/rgeo/rgeo-proj4 if it is still a problem. Thanks.
