### ISSUE TITLE
How can I transform a geometry?

### ISSUE THREAD

**Issue by allthesignals** [rgeo/rgeo#169]
How can I transform a geometry using pure RGeo? I'm working with RGeo::Geos::CAPIMultiPolygonImpl, and I'd like to transform it out of Mass StatePlane to WGS84. 

In PostGIS, I can `SELECT ST_Transform(walkshed, 4326) AS the_geom_wgs84`.

**Comment by timstallmann** [comment]
I think there's some documentation on this here http://daniel-azuma.com/articles/georails/part-4
Look like you need to use `RGeo::Feature.cast`?

**Comment by allthesignals** [comment]
Thanks, @timstallmann. Following the example exactly:

```ruby
wgs84_proj4 = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
wgs84_wkt = <<WKT
  GEOGCS["WGS 84",
    DATUM["WGS_1984",
      SPHEROID["WGS 84",6378137,298.257223563,
        AUTHORITY["EPSG","7030"]],
      AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
      AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.01745329251994328,
      AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
WKT

wgs84_factory = RGeo::Geographic.spherical_factory(:srid => 4326,
  :proj4 => wgs84_proj4, :coord_sys => wgs84_wkt)

shed = School.find(2).shed_20
shed.class #RGeo::Geos::CAPIMultiPolygonImpl
shed.srid #26986
shed.as_text.length #168438
RGeo::Feature.cast(shed, :factory => wgs84_factory, :project => true) #nil
```

It seems to always return nil. Maybe the CAPIMultiPolygonImpl is the wrong class? (http://www.rubydoc.info/github/rgeo/rgeo/RGeo/Geos/CAPIFactory). Does anyone know what CAPI stands for? 

This is my AR migration:
```ruby
    create_table :schools do |t|
     # ...
      t.multi_polygon :shed_20, srid: 26986, geographic: false
     #...
```

**Comment by martennilsson** [comment]
Hi @allthesignals. Did you ever manage to solve this? I have the exact same problem.

**Comment by mzagaja** [comment]
How to project a point from one system to another in a few easy steps:

```
# Get proj4 information from http://www.spatialreference.org/ref/epsg/4326/
# Create a point object with a factory that has the proj4 information about the projection
point = RGeo::Cartesian.factory(srid: 4326, proj4: '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs').point(42.3515351758408, -71.0970783233643)

# Setup target factory with proj4 information about the target projection
# http://www.spatialreference.org/ref/epsg/26986/
ma_factory = RGeo::Cartesian.factory(srid: 26986, proj4: '+proj=lcc +lat_1=42.68333333333333 +lat_2=41.71666666666667 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +datum=NAD83 +units=m +no_defs'

# Cast the point to the new factory
ma_point = RGeo::Feature.cast(point, factory: ma_factory, project: true)
2.3.3 :026 > ma_point = RGeo::Feature.cast(point, factory: ma_factory, project: true)
 => #<RGeo::Geos::CAPIPointImpl:0x3fed0695b7e8 "POINT (39369484.90102633 -1492444.686006059)">
```

3. ???
4. Profit!

**Comment by haroldofurtado** [comment]
But the problems is...:

`RGeo::Error::InvalidGeometry: LinearRing failed ring test`

**Comment by keithdoggett** [comment]
@mzagaja's solution worked in my tests, so I'm going to close this.

@haroldofurtado depending on which factories you're using, the validation constraints may be different between them so that could be an issue, but I believe it's unrelated to this issue.

**Comment by prebm** [comment]
For anyone coming here looking for a working example of a coordinate transformation or reprojection: 

With rgeo v3 the main functionality was moved to https://github.com/rgeo/rgeo-proj4. After including the gem the [above example](https://github.com/rgeo/rgeo/issues/169#issuecomment-321365444) still works. 

Additionally you fill find a great example in the Readme of [rgeo-proj4](https://github.com/rgeo/rgeo-proj4).
