### ISSUE TITLE
Rgeo spatial distance vis-a-vis reality poles apart

### ISSUE THREAD

**Issue by swaruprs** [rgeo/rgeo#171]
I am listing out nearby options from user location, in which distance plays a major role.  I chose rgeo to filter me out those options within 10 kms radius using ST_DWithin. However, I am getting significant margins in rgeo computed distance with respect to google map results.

Tried with the following sample points so far, and my results:

- Origin: (Lat, Long) - 12.918269,  77.635669

- Table

          RGeo Distance                   Lat, Long              GMap
             (in m)                                            (in Kms)

        4865.012768186506,         12.960146,  77.648496          7.4         
        4865.012768186506,         12.960146,  77.648496          7.4         
        2286.5466828101517,        12.936992,  77.627002          2.7            
        3672.943407131079,         12.949931,  77.645193          7.8           
        7913.722140288826,         12.848925,  77.651733         11.7              

- Model:

      class Locate < ApplicationRecord
	     scope :nearby, -> (origin, dist_in_meters = 10000) {
	       where("ST_DWithin(ST_GeographyFromText('SRID=4326;#{origin}'), position, #{dist_in_meters})")
	      } 
      end

- Controller:

      def nearby
        origin = geo_factory(77.635669,12.918269)
  	    options = Locate.nearby(origin)
  	    opt_dist = Array.new
  	      options.each do |option| 
  		    opt_dist << origin.distance(option.position)
          end
  		render json: { options: options, distance: opt_dist }, status: 200
	  end

      def geo_factory(ulong,ulat)
 	     RGeo::Geographic.spherical_factory(srid: 4326).point(ulong,ulat)
      end

- Schema:

       create_table "locates", force: :cascade do |t|
          t.integer   "user_id"
          t.geography "position",   limit: {:srid=>4326, :type=>"st_point", :geographic=>true}
          t.datetime  "created_at", null: false
          t.datetime  "updated_at", null: false
        end

- Initializer (rgeo.rb)

      RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
	
          # By default, use the GEOS implementation for spatial columns.
           config.default = RGeo::Geos.factory_generator

          # But use a geographic implementation for point columns.
           config.register(RGeo::Geographic.spherical_factory(srid: 4326), geo_type: "point")
      end

Assuming distance calculated in rgeo represents shortest path between two points which might not be the case in reality, hence being differing with gmap results. Can someone share if they had any similar experience?

Thanks in advance!

**Comment by biologistbrian** [comment]
I was having the same issue the other day.  Pretty sure the issue is the factory.  You need 3785 instead of 4326. Here's one link: https://stackoverflow.com/questions/20461394/why-am-i-seeing-a-great-discrepancy-between-distances-calculated-via-srid-4326-a

Google it some, I'm having trouble finding the link now but there's a good explanation out there somewhere by Azuma that I read. If I come across it again I'll update it.

**Comment by swaruprs** [comment]
Thanks a lot Brian :)

Surely, give it a try and update the results.

Best
Swarup

**Comment by biologistbrian** [comment]
PS-
I will tell you I actually went a different route personally and just used geocoder gem as I was using it in other parts of my app.  Worked out well.

**Comment by swaruprs** [comment]
Yeah, it looks quite promising. Are you getting closer results?

Regarding SRIDs, I am using point data and I found 4326 with geographic st_point type strongly recommended in various posts.

**Comment by swaruprs** [comment]
Yeah, it looks quite promising. Are you getting closer results?

Regarding SRIDs, I am using point data and I found 4326 with geographic
st_point type strongly recommended in various posts.

**Comment by biologistbrian** [comment]
Much closer.  Of course, you're talking about another dependency among other things.  Keep pushing.  You're using lon, lat format and not lat, lon, right? set to geographic and not geometry?  these are the typical errors you'll find, double check and play with lat/lon format, etc.  Found that thread: https://groups.google.com/forum/#!searchin/rgeo-users/distance$20wrong%7Csort:relevance/rgeo-users/ZNR0gF5iQLs/mxmWHpqbEgAJ
Azuma says 4326 shouldn't be off by more than a city block with two points in the same state.
Hmm.

**Comment by biologistbrian** [comment]
Oh - and if you do go geocoder route, you'll have to shorten the lat lon to float4 type data.  It can't handle all those decimal points!

**Comment by swaruprs** [comment]
Yeah, have checked that thread as well.
In my case. I have considered it in geo_factory(ulong, ulat) order only.

Moreover, if you see the points, max difference in GMap is around 12 kms,
which seems they must not be far off.

On 4326, Intuitively if I draw straight lines between two points they seem
closer to rgeo computed distance. But, roads are never straight in reality,
they might have typical left and right and then zigzag path which is always
more than the shortest distance between two points.

But, this is my pure assumption as I don't know how the distance and other
rgeo functions have been implemented. Someone please verify on this.


I am going to deep dive 3785 and geocoder route and update my results.
Meanwhile any suggestions are more than appreciated.

**Comment by swaruprs** [comment]
After further deep diving, found same results with Geocoder, which seems
closer to what I got with Rgeo

def dist
    dist = Geocoder::Calculations.distance_between( [12.918269, 77.635669],
 [12.936992,  77.627002], {:units => :km} )
    render json: dist
end

    Geocoder (kms)

4.859568922103168
4.859568922103168
2.283988085578286
3.668833461374978
7.904866853091865


Brian, Can you please verify!

**Comment by swaruprs** [comment]
Rgeo and geocoder values are "[as the crow flies](https://en.wikipedia.org/wiki/As_the_crow_flies)" unlike [OSRM](http://project-osrm.org/docs/v5.9.1/api/#nearest-service) or google road path distance.
