### ISSUE TITLE
Status of mysql ST_* functions?

### ISSUE THREAD

**Issue by Shkrt** [rgeo/rgeo#175]
Readme file at https://github.com/rgeo/rgeo/blob/master/Spatial_Programming_With_RGeo.md states that 

> What MySQL lacks is support for most of the advanced spatial geometry functions such as the relational operators (e.g. ST_Intersects(), ST_Contains(), etc.), so you will not be able to perform complex geometric calculations using the database engine.

But this is not actual anymore, since mysql has support for that types of functions: https://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html#function_st-contains

So, what is the exact status of this feature, are the ST_* functions supported by rgeo's mysql adapter and should docs be updated?

**Comment by teeparham** [comment]
Good question! The `rgeo` gem does not do anything with specific databases. I personally don't use MySql, so I don't know.

Perhaps the MySql adapter gem would be a good place to ask this question:  https://github.com/rgeo/activerecord-mysql2spatial-adapter

Pull requests to the documentation are welcome.
