### ISSUE TITLE
*QUESTION*  Who is using RGeo?

### ISSUE THREAD

**Issue by teeparham** [rgeo/rgeo#186]
Hello! I'm curious who uses `rgeo` and/or any [related gems](https://github.com/rgeo).

Daniel Azuma and I are going to be talking about `rgeo` on an upcoming podcast, and I'd like to be able to answer this very question. If you or your company is using an rgeo gem, please comment here. Please include the name of your company, a link to your website, which gem(s) you're using, and a brief description (if you'd like).

🌐  Thank you!

(I'll start)

Company | Link | Gems | Description
--------- | ---- | ---- | ----------
Neighborland | https://neighborland.com | activerecord-postgis-adapter, rgeo, rgeo-geojson | Saving geocoded points, saving polygons, importing/exporting geojson, querying nearby points, building polygons for queries

**Comment by jjgreen** [comment]
[Seaview Sensing](http://www.seaviewsensing.com/) will soon be launching a Rails/OpenLayers based data-viewer for oceanic data, which uses _rgeo_ and _rgeo-json_

![svdv-screenshot](https://user-images.githubusercontent.com/3464626/37236473-e3ae709a-23ff-11e8-81fa-998073f531b6.png)

We think ithey're great -- thanks a lot!

**Comment by pedros007** [comment]
I use activerecord-postgis-adapter, rgeo and rgeo-geojson on a project at [DigitalGlobe](http://www.digitalglobe.com/) where I need to comb through a [large image archive](http://blog.digitalglobe.com/industry/digitalglobe-moves-to-the-cloud-with-aws-snowmobile/).

**Comment by fordfischer** [comment]
Company | Link | Gems | Description
-- | -- | -- | --
Rudolph Data | https://www.prorudolph.com | activerecord-postgis-adapter, rgeo, rgeo-geojson, rgeo-shapefile, rgeo-proj4 | Saving geocoded points, importing shapefiles, creating/saving polygons, querying points inside/intersecting with polygons

**Comment by beaorn** [comment]
| Company           | Link                                               | Gems                                        | Description         |
| ---------------  | ------------------------------- | ----------------------------- | ---------------- |
| Ag Developer     | https://www.agdeveloper.com   | activerecord-postgis-adapter, rgeo, rgeo-geojson, rgeo-shapefile, rgeo-proj4 | Saving geocoded points, importing shapefiles, creating/saving polygons, importing/exporting geojson, querying nearby points, building polygons for queries, intersections

**Comment by mjy** [comment]
| Company | Link | Gems | Description|
|-----------|-----|-------|-------------|
| TaxonWorks / Species File Group | http://taxonworks.org | rgeo; rgeo-geojson; rgeo-proj4; rgeo-shapefile; ffi-geos | Our group builds open-source biodiversity informatics tools, we use these gems for georeferencing museum specimens and their collection localities- save points, (multi)polys, lines, compute intersections and nearby, serve geojson, load gazetteers |

**Comment by beaorn** [comment]
@teeparham are you able to comment to on name of podcast and expected date to listen? Would love to hear you and @dazuma talk about rgeo and related gems. Thanks

**Comment by dazuma** [comment]
@beaorn We're recording in the next few days, but it will be a few weeks before it's actually available. (Since RailsConf is getting close and people are busy, I'm expecting some amount of delay.) We'll comment here with the link when we have it.

**Comment by teeparham** [comment]
Thanks everyone! I added a Gallery wiki page here: https://github.com/rgeo/rgeo/wiki/Gallery

Feel free to add/update.

**Comment by dazuma** [comment]
The podcast is online here: https://devchat.tv/ruby-rogues/rr-356-geospatial-programming-in-ruby-with-daniel-azuma-and-tee-perham

**Comment by MarchChadwick** [comment]
Daniel, Tee, RGeo is great!  We at Zoner.city are thankful to you.  Our objective is to improve decision making in architecture and reduce environmental impact with better building design.  We hope to grow and contribute to your excellent and meaningful work.  March Chadwick
