### ISSUE TITLE
Unable to load the library on Heroku

### ISSUE THREAD

**Issue by volkanunsal** [rgeo/rgeo#195]
In the last few days, this library stopped working on Heroku for me. The root cause might be the Heroku buildpack, but that seems to build correctly and I can see all the binaries on the server when I log into it. That's why I wanted to check if there might be a change in this gem to have caused this issue. 

The native extensions for this library appear to be missing:

```
irb(main):001:0>       require "rgeo/geos/geos_c_impl"
LoadError: cannot load such file -- rgeo/geos/geos_c_impl
	from (irb):1
irb(main):002:0>
```

Here is the issue I created on the buildpack repo:

https://github.com/cyberdelia/heroku-geo-buildpack/issues/50

**Comment by volkanunsal** [comment]
Geos headers appear to be in the app. But RGeo doesn't seem to be able to find them:

```
~ $ find ./ -name 'geos_c.h'
  ./.heroku/vendor/include/geos_c.h
```

**Comment by teeparham** [comment]
This seems to be resolved & is not an issue with this gem. Closing.
