### ISSUE TITLE
RGeo::Geos.supported? failing

### ISSUE THREAD

**Issue by strtwtsn** [rgeo/rgeo#227]
Trying to get the rgeo gem to recognise geos on an ubuntu 16.04 system.

I have the following packages installed:-

libgeos-dev, libgeos++-dev and libgeos-3.7.1

geos-config --version
3.7.1
I have a symlink in /usr/lib which points to the location of the version specific version in

lrwxrwxrwx  1 root root   42 Oct 21 18:05 libgeos.so -> /usr/lib/x86_64-linux-gnu/libgeos-3.7.1.so
Have run the following commands

```
gem uninstall rgeo
gem install rgeo -- --with-geos-dir=/usr/lib
```

However when I run the following it fails

```
RAILS_ENV=staging bundle exec irb
require 'rgeo'
RGeo::Geos.supported?
 => false
```

What am I doing wrong? Have searched the various posts about this which has led me to install the -dev package and create the symlink, but still it doesnt work.

Have also added /usr/lib to /etc/ld.so.conf.d/ and run ldconfig but without success.

**Comment by strtwtsn** [comment]
RAILS_ENV=staging bundle exec irb
2.5.0 :001 > require 'rgeo'
 => true 
2.5.0 :002 > RGeo::Geos.supported?
 => true 
2.5.0 :003 > 

shows it working, but 

Loading staging environment (Rails 5.2.0)
2.5.0 :001 > require 'rgeo'
 => false 
2.5.0 :002 > RGeo::Geos.supported?
 => false

fails

and the app still shows 

RGeo::Error::RGeoError (GEOS is not available, but is required for correct interpretation of polygons in shapefiles.)

**Comment by BuonOmo** [comment]
Hi @strtwtsn,

There are some contradictions in your messages. The second one says that `RAILS_ENV=staging bundle exec irb` is working whilst the first one doesn't.

Hence I'll consider your last message: what is the difference (apart from `supported?` returning `true` then `false`) between the two snippets you are showing ?

> RGeo::Error::RGeoError (GEOS is not available, but is required for correct interpretation of polygons in shapefiles.)

This error comes from `rgeo-shapefile`, what is your stack ? Maybe the error you have encountered is not about the `rgeo` core project.

Please clarify your issue and we'll be able to provide correct help!

**Comment by SampsonCrowley** [comment]
@strtwtsn did you reinstall rgeo after installing `geos`?

For me I could not get `true` to be shown, but i had not installed `geos` (on arch linux) until after running bundle; expecting rgeo to use `exec` statements instead of compiling it into the gem itself. after running `gem uninstall rgeo` and then re-running `bundle`, `supported?` then returned true for me

**Comment by keithdoggett** [comment]
@SampsonCrowley that's a good point, and I will add that to the README. I believe the issue @strtwtsn is having is related to the `spring` gem. This is usually the case when calling `RGeo::Geos.supported?` in `irb` returns `true`, but calling it in the `rails console` returns `false`, which I believe is what's happening here.

**Comment by SampsonCrowley** [comment]
@keithdoggett also a good point. Forgot about the part where for him it's working in IRB, but not Rails Console. 99% of the time, that's usually a spring issue, unless they're aware of how spring works or it's persistent through stopping spring

**Comment by andrewa28** [comment]
Hello @strtwtsn to fix this issue i needed to run these commands on ubuntu machine, then re-install rgeo gem
```
sudo apt update
sudo apt install libgeos++-dev libgeos-3.8.0 libgeos-c1v5 libgeos-dev libgeos-doc
gem unintsall rgeo
gem install rgeo
```
