### ISSUE TITLE
CAPI or FFI, not both

### ISSUE THREAD

**Issue by BuonOmo** [rgeo/rgeo#233]
Nowadays, the RGeo codebase is huge. And there are tons of ways to do the same thing. A user has to first understand what are the choices, then make a choice, and only then can he start using `RGeo` correctly.

I've been wondering _How_ can we reduce it, and there are plenty solutions. One of those IMHO, is to remove the `ffi-geos` variant.

## Why?

`ffi` and `capi` native interface serve the same factory, and they have very similar goals. However, the capi version has much better performances:

```ruby
# frozen_string_literal: true

require "benchmark/ips"
require "net/http"
require "rgeo"
require "rgeo-geojson"

# Install GEOS to run this benchmark.
exit 1 unless RGeo::Geos.capi_supported?

# https://github.com/gregoiredavid/france-geojson/blob/master/departements/38-isere/departement-38-isere.geojson
geojson = Net::HTTP.get(URI("https://raw.githubusercontent.com/gregoiredavid/france-geojson/master/departements/38-isere/departement-38-isere.geojson"))

ffi_factory   = RGeo::Cartesian.preferred_factory(native_interface: :ffi)
capi_factory  = RGeo::Cartesian.preferred_factory
ruby_factory  = RGeo::Cartesian.simple_factory
ffi_geometry  = RGeo::GeoJSON.decode(geojson, geo_factory: ffi_factory).geometry
capi_geometry = RGeo::GeoJSON.decode(geojson, geo_factory: capi_factory).geometry
ruby_geometry = RGeo::GeoJSON.decode(geojson, geo_factory: ruby_factory).geometry
ffi_point     = ffi_factory.point(5.72662, 45.18203)
capi_point    = capi_factory.point(5.72662, 45.18203)
ruby_point    = ruby_factory.point(5.72662, 45.18203)

puts "POLYGON CONTAINS POINT\n\n"

Benchmark.ips do |x|
  x.report("with CAPI GEOS") { capi_geometry.contains?(capi_point) }
  x.report("with FFI GEOS") { ffi_geometry.contains?(ffi_point) }
  x.report("simple ruby") { ruby_geometry.contains?(ruby_point) }

  x.compare!
end

puts "\n\nPOLYGON INSTANCIATION FROM GEOJSON\n\n"

Benchmark.ips do |x|
  x.report("FFI create polygon") { RGeo::GeoJSON.decode(geojson, geo_factory: ffi_factory).geometry }
  x.report("CAPI create polygon") { RGeo::GeoJSON.decode(geojson, geo_factory: capi_factory).geometry }

  x.compare!
end
```

On a MacBook pro 1,4 GHz Quad-Core Intel Core i5:

```
POLYGON CONTAINS POINT

Warming up --------------------------------------
      with CAPI GEOS   561.570k i/100ms
       with FFI GEOS    72.448k i/100ms
         simple ruby    92.000  i/100ms
Calculating -------------------------------------
      with CAPI GEOS      5.559M (± 3.9%) i/s -     28.078M in   5.059348s
       with FFI GEOS    718.911k (± 4.0%) i/s -      3.622M in   5.048048s
         simple ruby    998.699  (± 2.2%) i/s -      5.060k in   5.069308s

Comparison:
      with CAPI GEOS:  5559335.0 i/s
       with FFI GEOS:   718910.6 i/s - 7.73x  (± 0.00) slower
         simple ruby:      998.7 i/s - 5566.58x  (± 0.00) slower



POLYGON INSTANCIATION FROM GEOJSON

Warming up --------------------------------------
  FFI create polygon     1.000  i/100ms
 CAPI create polygon    13.000  i/100ms
Calculating -------------------------------------
  FFI create polygon      4.474  (± 0.0%) i/s -     23.000  in   5.145574s
 CAPI create polygon    137.381  (± 7.3%) i/s -    689.000  in   5.045791s

Comparison:
 CAPI create polygon:      137.4 i/s
  FFI create polygon:        4.5 i/s - 30.71x  (± 0.00) slower
```

Note that before making this decision we may need to do more benchmarks !

## A drawback

There are some projects that depends on `ffi-geos`, such as the neat https://github.com/benbalter/geojson-diff. For these projects, `rgeo` usage is transparent to the user, since they **do not have to care about installing geos**.

However, I think there could be a simple solution to this issue. Making RGeo work out of the box, with the CAPI. The idea comes from https://github.com/sass/sassc-ruby which has an `ext/` folder pointing to `libsass` directly. Which has some benefits:

1. You only `gem install sassc` and do not need to care about libsass
2. The `libsass` version is defined by the `sassc` gem, hence no compatibility issues for different versions.

On the other hand, the `sassc` gem uses ffi itself. And there must be a lot of good reasons to use ffi over capi, one being maintainability, and other ones I don't know.

There also may be many more drawbacks that I don't know about...

Hence I'm opening this issue for discussion on that topic.

**Comment by dazuma** [comment]
For historical context, the original reason for the FFI implementation was JRuby compatibility.

**Comment by keithdoggett** [comment]
I don't think it makes sense to get rid of the FFI implementation, but I think we need to do a few things to help out the users/reduce some complexity:

1) Document the differences between the factories in some type of table. The existing documentation should help a lot with this, but having the differences in terms of what methods are available for each factory can help users determine the trade-offs of each.

2) Using the above as a roadmap, implement the missing features for each factory and get all of them to at least have SFS compliance. I'm hoping that accomplishing this will lend itself to some code reduction/simplification throughout the project.

2 will definitely be a bit of a lift, but I think with the way this winter's shaping up I'll have a good amount of time to work on this.

I can start trying to get that table together in the meantime if you think this makes sense.

**Comment by BuonOmo** [comment]
@keithdoggett this definitely makes sense. I'll have some time in the current week to make a first version of a _which factory should i use ?_ documentation. I'll give you a link to that since this may be the best place to integrate such a table. Maybe this table should be generated by a script as well (if there is an error or nil, mark the column failed, otherwise ok) since there are a lot of methods (say 15+) times a lot of factories (6) (= at least 90 entries), which will make it very tedious to maintain.

And the support of JRuby is a great reason to maintain it indeed ! I guess if one day the core team gets tougher we could replace this version by a native jts binding. Then we'll have fast implementation for both JRuby and Ruby, and we'll be able to ship ready to run, fast-paced RGeo out of the box. However, now is not a time to do such a thing IMHO

**Comment by BuonOmo** [comment]
Closing since:
- we want to keep FFI support for JRuby users
- we want to keep CAPI for the performance gap

The next step in clarifying our GEOS usage can be found [there](https://github.com/rgeo/rgeo/issues/272) and is part of our 3.0 roadmap.
