### ISSUE TITLE
[Question] Creating Shapefile

### ISSUE THREAD

**Issue by ervinismu** [rgeo/rgeo#237]
can i create a .shp (shapefile) using rgeo gem? if yes,
Are there any sources for reading that I can study?

thank you

**Comment by keithdoggett** [comment]
Hi @ervinismu currently we do not support creating shapefiles in the `rgeo-shapefile` gem. One solution could be to write GeoJSON files with `rgeo-geojson` and then use a program like `ogr2ogr` to convert between formats.

Pull requests are welcome if you'd be interested in creating a shapefile writer!
