### ISSUE TITLE
RGeo::Geos.supported? false despite linking successfully to geos lib

### ISSUE THREAD

**Issue by quidquid** [rgeo/rgeo#26]
Hi, I'm having a devil of a time getting GEOS support under Ubuntu (version 5/lenny). It's working great on my OSX dev machine but the production environment won't have it. Geos and proj4 are installed locally, I send the prefixes to gem install, the native extensions are compiled and linked to both, and yet rgeo doesn't see it! Here's a log:

https://gist.github.com/2564023

I thought it might be a gem caching issue but have tried clearing caches, uninstalling & rebuilding several times. Any ideas where to look? Thanks!

**Comment by gamut** [comment]
Jesus.  Thank you wrkrb33!  That last one was the solution for me as well, ubuntu 14.04

**Comment by jeremieweldin** [comment]
>Regarding your issue, two things. First, you should not use --with-geos-dir when geos is installed in a standard location such as /usr. (And in fact one reason you're having problems is that you're setting it to /usr/lib rather than /usr).

Does this mean that RGeo expects there to be a lib dir in the directory specified? 

How does this affect systems like Amazon Linux where geos and proj are installed to /usr/lib64?
I am having a hard time getting RGeo::Geos.supported? to return true. I have installed both geos and proj via yum and am specifying both with directory of /usr/lib64. I have even symlinked them to the names without the version numbers.

**Comment by jeremieweldin** [comment]
I even added a link from /usr/lib/libgeos.so to the /usr/lib64 file. Same for libproj. Then removed the option to specify dirs, uninstalled rgeo and reinstalled it. No dice.

**Comment by JLeeAgape** [comment]
Just got it working after 2 hours of tinkering.
For Ubuntu 14.04, libgeos 3.4.2, and RGeo 0.3.20 in Rails 4.2.1:
```sh
sudo apt-get -y install libgeos-3.4.2 libgeos-dev libproj0 libproj-dev
sudo ln -s /usr/lib/libgeos-3.4.2.so /usr/lib/libgeos.so
sudo ln -s /usr/lib/libgeos-3.4.2.so /usr/lib/libgeos.so.1
```
In the Gemfile:
```ruby
gem 'rgeo', require: false
```

Good luck!

**Comment by jeremieweldin** [comment]
My issue was not having the -devel versions of geos and proj installed. I was able to install with --with_xx_dir=/usr/lib64.

**Comment by AndreasHeiberg** [comment]
> /usr/lib$ sudo ln -s libgeos-3.4.2.so libgeos.so
>
> Once I had done that and rebuilt (not absolutely certain the rebuild was necessary) then finally things worked as expected.

This is the only thing that solved it for me

**Comment by benjii** [comment]
Apologies if I am hijacking this thread, but I am tearing my hair out a bit here... I am having the same problem as many others here, in that I am unable to get rgeos to link to libgeos.

Having tried all of the solutions above, I did discover this;

    crags@CRAGS-SERVER:~/crags$ gem install rgeo --verbose

*snip*

    Building native extensions.  This could take a while...
    /home/crags/.rbenv/versions/2.1.2/bin/ruby extconf.rb
    checking for geos_c.h... yes
    checking for GEOSSetSRID_r() in geos_c.h... no
    checking for GEOSPreparedContains_r() in geos_c.h... no
    checking for GEOSPreparedDisjoint_r() in geos_c.h... no
    checking for GEOSWKTWriter_setOutputDimension_r() in geos_c.h... no
    checking for rb_memhash() in ruby.h... yes
    **** WARNING: Unable to find GEOS headers or GEOS version is too old.
    **** Compiling without GEOS support.

This line

    checking for GEOSSetSRID_r() in geos_c.h... no

Is what is what I am focussing on. I do have two copies of geos_c.h;

    crags@CRAGS-SERVER:~/crags$ locate geos_c.h
    /usr/include/geos_c.h
    /usr/local/include/geos_c.h

Both of which *appear* to have the required function (from a simple grep).

But no dice - no matter what I do the rgeo native extension compilation will always compile without GEOS support...

Any help would be _greatly_ appreciated!

Ben

**Comment by andreimc** [comment]
@JLeeAgape saved me lots of time here :+1:

**Comment by jszwedko** [comment]
I'm in the same boat as @benjii. The header file exists with the functions required, but I get the same output from `gem install rgeo --verbose`.

**Comment by jszwedko** [comment]
Scratch that, `sudo ln -s libgeos-3.4.2.so libgeos.so` as noted above worked for me.

**Comment by anke1460** [comment]
@JLeeAgape thx! It works for me

**Comment by gavit** [comment]
I got geos, geos-dev, proj, proj-dev installed.
However mine still fails at factory:
    irb
    Ignoring eventmachine-1.0.8 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.8
    Ignoring pg-0.18.3 because its extensions are not built.  Try: gem pristine pg --version 0.18.3
    Ignoring thin-1.6.4 because its extensions are not built.  Try: gem pristine thin --version 1.6.4
    Ignoring yajl-ruby-1.2.1 because its extensions are not built.  Try: gem pristine yajl-ruby --version 1.2.1
    irb(main):001:0> require 'rubygems'
    => false
    irb(main):002:0> require 'rgeo/yaml'
    => true
    irb(main):003:0> require 'rgeo/version'
    => true
    irb(main):004:0> require 'rgeo/error'
    => true
    irb(main):005:0> require 'rgeo/feature'
    => true
    irb(main):006:0> require 'rgeo/coord_sys'
    => true
    irb(main):007:0> require 'rgeo/impl_helper'
    => true
    irb(main):008:0> require 'rgeo/wkrep'
    => true
    irb(main):009:0> require 'rgeo/geos/utils'
    => true
    irb(main):010:0> require 'rgeo/geos/factory'
    LoadError: cannot load such file -- rgeo/geos/factory
    	from /usr/local/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from /usr/local/rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from (irb):10
    	from /usr/local/rbenv/versions/2.2.3/bin/irb:11:in `<main>'
    irb(main):011:0> require 'rgeo/geos/interface'
    => true
    irb(main):012:0> require 'rgeo/geos/geos_c_impl'
    => true
    irb(main):013:0>

**Comment by arthurbryant** [comment]
Great help from the guys' suggestions. I am not using Ubuntu but Amazon Linux, it took me a while to finally made it work. 

Enviornment: Amazon Linux

### Point
You need to install the dependency libraries before install rgeo.

```
yum update
yum install geos geos-devel

# create link (maybe not necessary)
sudo ln -s /usr/lib64/libgeos-3.4.2.so /usr/lib/libgeos.so

# install proj4(I could not find the yum source)
wget http://download.osgeo.org/proj/proj-4.9.1.tar.gz
wget http://download.osgeo.org/proj/proj-datumgrid-1.5.zip
tar zxvf proj-4.9.1.tar.gz
cd proj-4.9.1/nad
unzip ../../proj-datumgrid-1.5.zip
cd ..
./configure  
make
sudo make install

# update libraries link
sudo su
echo /usr/local/lib >> /etc/ld.so.conf
exit
sudo ldconfig

# deploy your application and install rgeo
gem uninstall rgeo && gem install rgeo
```  

### References 
https://github.com/rgeo/rgeo
http://en.joysword.com/posts/2015/05/configuring_geo_spatial_stack_on_amazon_linux/

**Comment by januszm** [comment]
Amazon Linux 2023, I can't get RGeo to work with GEOS after succesful compilation and installation of all necessary files:

```
# geos-config --prefix
/usr
# geos-config --libs
-L/usr/lib64 -lgeos
# geos-config --includes
/usr/include
# geos-config --ldflags
-L/usr/lib64


# ls -la /usr/lib64/libgeos*
lrwxrwxrwx. 1 root root  /usr/lib64/libgeos_c.so -> libgeos_c.so.1
lrwxrwxrwx. 1 root root  /usr/lib64/libgeos_c.so.1 -> libgeos_c.so.1.18.0
-rwxr-xr-x. 1 root root    /usr/lib64/libgeos_c.so.1.18.0
lrwxrwxrwx. 1 root root  /usr/lib64/libgeos.so -> libgeos.so.3.12.0
-rwxr-xr-x. 1 root root   /usr/lib64/libgeos.so.3.12.0

# ls -la /usr/include/geos*
-rw-r--r--.  1 root root   /usr/include/geos_c.h
-rw-r--r--.  1 root root   /usr/include/geos.h

/usr/include/geos:
total 272
drwxr-xr-x.  6 root root  algorithm
-rw-r--r--.  1 root root   constants.h
drwxr-xr-x.  2 root root  coverage
drwxr-xr-x.  2 root root   edgegraph
-rw-r--r--.  1 root root    export.h
...
-rw-r--r--.  1 root root   version.h
```

```
gem uninstall rgeo
gem install rgeo

irb(main):002> require "rgeo"
=> true
irb(main):003> RGeo::Geos.supported?
=> false
```

any ideas why RGeo/Ruby still cannot see GEOS files although their in their most basic location, in /usr (not even /usr/local), all owned by root with read access.

**Comment by januszm** [comment]
more info from `gem install --verbose rgeo` on Amazon Linux 2023 with geos compiled, and Ruby 3.2

```
Building native extensions. This could take a while...
current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
["/usr/bin/ruby3.2", "-I/usr/share/ruby3.2-rubygems", "extconf.rb"]
checking for geos-config... yes
Using GEOS compile configuration from /usr/local/bin/geos-config
checking for geos_c.h... yes
checking for GEOSSetSRID_r() in geos_c.h... yes
checking for GEOSPreparedContains_r() in geos_c.h... yes
checking for GEOSPreparedDisjoint_r() in geos_c.h... yes
checking for GEOSUnaryUnion_r() in geos_c.h... yes
checking for GEOSCoordSeq_isCCW_r() in geos_c.h... yes
checking for rb_memhash() in ruby.h... yes
checking for rb_gc_mark_movable() in ruby.h... yes
creating Makefile
current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
["make", "DESTDIR=", "sitearchdir=./.gem.20231026-74813-mbjmdr", "sitelibdir=./.gem.20231026-74813-mbjmdr", "clean"]

current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
["make", "DESTDIR=", "sitearchdir=./.gem.20231026-74813-mbjmdr", "sitelibdir=./.gem.20231026-74813-mbjmdr"]
compiling analysis.c
compiling coordinates.c
compiling errors.c
compiling factory.c
compiling geometry.c
compiling geometry_collection.c
compiling globals.c
compiling line_string.c
compiling main.c
compiling point.c
compiling polygon.c
compiling ruby_more.c
linking shared-object rgeo/geos/geos_c_impl.so
current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
["make", "DESTDIR=", "sitearchdir=./.gem.20231026-74813-mbjmdr", "sitelibdir=./.gem.20231026-74813-mbjmdr", "install"]
/usr/bin/install -c -m 0755 geos_c_impl.so ./.gem.20231026-74813-mbjmdr/rgeo/geos
current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
["make", "DESTDIR=", "sitearchdir=./.gem.20231026-74813-mbjmdr", "sitelibdir=./.gem.20231026-74813-mbjmdr", "clean"]

current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
/usr/bin/ruby3.2 -I/usr/share/ruby3.2-rubygems extconf.rb
current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
make DESTDIR\= sitearchdir\=./.gem.20231026-74813-mbjmdr sitelibdir\=./.gem.20231026-74813-mbjmdr clean
current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
make DESTDIR\= sitearchdir\=./.gem.20231026-74813-mbjmdr sitelibdir\=./.gem.20231026-74813-mbjmdr
current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
make DESTDIR\= sitearchdir\=./.gem.20231026-74813-mbjmdr sitelibdir\=./.gem.20231026-74813-mbjmdr install
current directory: /usr/local/share/ruby3.2-gems/gems/rgeo-3.0.0/ext/geos_c_impl
make DESTDIR\= sitearchdir\=./.gem.20231026-74813-mbjmdr sitelibdir\=./.gem.20231026-74813-mbjmdr clean
Successfully installed rgeo-3.0.0

# irb
irb(main):001> require "rgeo"
=> true
irb(main):002> RGeo::Geos.supported?
=> false
```

**Comment by januszm** [comment]
On Amazon Linux 2023 I ended up adding `require: false` in Gemfile
```
gem 'rgeo', require: false
```

and specified the requires for rgeo as follows, in `config/initializers/geos.rb`

```ruby
require 'rgeo/feature'
require 'rgeo/impl_helper'
require 'rgeo/geos/geos_c_impl'
require "rgeo"
```
