### ISSUE TITLE
 RGeo::Geographic.simple_mercator_factory ignores lenient flags

### ISSUE THREAD

**Issue by earnold** [rgeo/rgeo#277]
I am having an issue with the classic `LinearRing failed ring test` when I use a simple mercator factory.  I've noticed that several of the closed issues on this topic suggest setting one of the possible lenient flags, i.e. `lenient_multi_polygon_assertions: true, uses_lenient_assertions:true`

However, this did not solve my issue. Looking under the hood, it seems as if [the factor method does not pass along these options](https://github.com/rgeo/rgeo/blob/v2.3.0/lib/rgeo/geographic/interface.rb#L216). 

Is this a deliberate design choice? And if so, could anyone point me in the direction of getting a more lenient behavior with a simple mercator projection & a potentially self-intersecting multipolygon?

**Comment by earnold** [comment]
I've posted more details about a related issue on stackoverflow if that is helpful: https://stackoverflow.com/questions/69827860/issue-with-rgeo-geojson-linearring-failed-ring-test-epsg-3857-vs-epsg-432

**Comment by thestelz** [comment]
@earnold I've had the same issue and I have created the following monkey patch. I was going to put in a pull request about fixing this, but it they are in the progress of revamping the gem, so I wanted to wait.

I pulled this from my project, so it should work as a drop in replacement. 

```ruby
# Monkey patch for issues with lenient assertions for RGeo.
#
# /lib/extensions/rgeo/factory.rb
#
# ruby '2.5.3'
# gem 'rails', '5.2.4.6'
# gem 'rgeo', '2.1.1'
#
# This will allow:
#   factory = RGeo::Geographic.simple_mercator_factory(uses_lenient_assertions: true, lenient_multi_polygon_assertions: true)
#   factory.set_property(:uses_lenient_assertions, true)
#
module RGeo
  module Geographic
    class Factory
      def set_property(prop, value)
        case prop
          when :has_z_coordinate
            @support_z = value
          when :has_m_coordinate
            @support_m = value
          when :uses_lenient_assertions
            @lenient_assertions = value
          when :buffer_resolution
            @buffer_resolution = value
          when :is_geographic
            value
        end
      end
    end
  end
end
```

I hope this helps!

(I'll also post on the S.O. question as well)

**Comment by earnold** [comment]
@thestelz Awesome! Thank you. This is helpful.

**Comment by keithdoggett** [comment]
@earnold thanks for the bug report. I'm able to reproduce this behavior and thanks @thestelz for the fix. We are getting rid of this behavior in version 3, but I suppose it would be worthwhile to get a patch for this in the meantime.

@thestelz if you want to open a PR that would be appreciated, otherwise I may have time to get to this next week.

**Comment by earnold** [comment]
@keithdoggett Is there a public read map for v3? I'm starting to use this gem in more and more of my current project. I'd love to know more about its direction, and potentially see if there are places I could help out.

**Comment by thestelz** [comment]
@keithdoggett I'll see if I can get to it. We are in the progress of moving all of our projects to docker, so I'll see if I can squeeze in some time to fix that (I might need some help with that, but I'll put that all in a pull request).

@earnold I think everything so far can be found in #247.

**Comment by keithdoggett** [comment]
@earnold the issue mentioned above is the roadmap and any issues tagged with 3.0 have more of a description about what needs to be done. Any help is appreciated thanks!
