### ISSUE TITLE
Concurrency problems with single app-wide factory?

### ISSUE THREAD

**Issue by durkie** [rgeo/rgeo#307]
Hi RGeo folks -- I recently switched to declaring a single RGeo factory in `config/initializers/rgeo.rb` as recommended in the docs, along the lines of simply `RF = RGeo::Geos.factory(srid: 4326)`, and then I reference `RF` in various models/services throughout my app.

Around the same time, I noticed that many of my Sidekiq jobs seem to be failing intermittently with strange parsing errors, and I just put it together that this seems like it might be related to having a single, app-wide factory:
```
sidekiq_1      | 2022-05-20T01:06:57.208Z pid=1 tid=gp7mdij15 WARN: NoMethodError: undefined method `scan_until' for nil:NilClass
sidekiq_1      | 2022-05-20T01:06:57.210Z pid=1 tid=gp7mdij15 WARN: /usr/src/app/vendor/bundle/ruby/2.6.0/gems/rgeo-2.1.1/lib/rgeo/wkrep/wkt_parser.rb:396:in `next_token'
sidekiq_1      | /usr/src/app/vendor/bundle/ruby/2.6.0/gems/rgeo-2.1.1/lib/rgeo/wkrep/wkt_parser.rb:223:in `parse_coords'
sidekiq_1      | /usr/src/app/vendor/bundle/ruby/2.6.0/gems/rgeo-2.1.1/lib/rgeo/wkrep/wkt_parser.rb:267:in `parse_point'
sidekiq_1      | /usr/src/app/vendor/bundle/ruby/2.6.0/gems/rgeo-2.1.1/lib/rgeo/wkrep/wkt_parser.rb:202:in `parse_type_tag'
sidekiq_1      | /usr/src/app/vendor/bundle/ruby/2.6.0/gems/rgeo-2.1.1/lib/rgeo/wkrep/wkt_parser.rb:133:in `parse'
sidekiq_1      | /usr/src/app/vendor/bundle/ruby/2.6.0/gems/rgeo-2.1.1/lib/rgeo/geos/capi_factory.rb:288:in `parse_wkt'
sidekiq_1      | /usr/src/app/app/lib/osm.rb:132:in `block in get_sqlite_streets'
```

Looking at `wkt_parser.rb:396`, it looks like the error is that `@scanner` is nil, which seems like it can only happen if some other job called `clean_scanner` (`wkt_parser.rb:384`) at just the right time and set `@scanner` to nil right as my current job needed `@scanner.scan_until()`

Does this seem like a reasonable conclusion? I have dozens of sidekiq jobs running at any given time, each processing geospatial data, so it seems like a timing bug that could be expected to happen.

Have I reached the limits of using this pattern? Should I go back to creating a factory from scratch every time I need to use it?
Is there some other way to approach this? This is with Ruby 2.6.5 and RGeo 2.1.1 on Linux.

**Comment by keithdoggett** [comment]
@durkie thanks for the detailed issue. I think your conclusion about what's causing the issue is reasonable. We do use the reentrant API in our CAPI which should allow for thread-safe operations, but as you pointed out, this bug is introduced in the Ruby interface.

I think for now, you will probably want to use a new factory in each of your sidekiq jobs if this is happening a lot, but we'll try to look into a way to allow better support for concurrency.
