### ISSUE TITLE
With geos 3.12, the CAPI factory enables Z geometries

### ISSUE THREAD

**Issue by Tristramg** [rgeo/rgeo#360]
### Steps to reproduce

Install rgeo built against geos 3.12. Here is a Dockerfile to reproduce it.

```dockerfile
FROM ruby:3.2.2-bullseye

RUN apt update && apt install --yes cmake ruby-dev

RUN wget https://download.osgeo.org/geos/geos-3.12.0.tar.bz2
RUN tar -xf geos-3.12.0.tar.bz2
RUN mkdir geos-3.12.0/build && cd geos-3.12.0/build && cmake -DCMAKE_BUILD_TYPE=Release ..
RUN cd geos-3.12.0/build && make && make install
RUN ldconfig
RUN gem install rgeo

CMD ruby -e "require 'rgeo'; puts RGeo::Geos.capi_supported? ? RGeo::Cartesian.preferred_factory(srid: 4326).point(1, 1).as_text : 'CAPI not supported'"
```

In a shell:

```sh
docker build .  --tag 'rgeo_geos_3_12'
docker run rgeo_geos_3_12
```

### Expected behavior

Creates a geometry without Z. It displays `POINT (1 1)`

### Actual behavior

Creates a geometry with Z: `POINT Z (1 1 0)`

### System configuration

**Ruby version**:

3.2.2

**OS**:

Ubuntu bullseye in docker.
Geos 3.12 build from sources.

It also happens on MacOS with geos installed through brew.

**Comment by buffpojken** [comment]
I second this, this happens with multipolygons as well in an unexpected way. 

We pass the following geometry to RGeo: 

`MULTIPOLYGON(((12.932783211827351 55.52388199800951,12.93245550269099 55.52385006659112,12.932511159135071 55.52366627893948,12.932034283234547 55.523792667409026,12.932249636217353 55.52408517418492,12.932380445341693 55.52409792424644,12.932708140512728 55.52412986477694,12.932783211827351 55.52388199800951)),((12.934160764140689 55.524585414273915,12.935069804474448 55.52439776732449,12.935081366292575 55.52435334973056,12.935114165594179 55.5243561507144,12.935140137641318 55.52425637035675,12.935184353995986 55.524086684745086,12.935187805705446 55.52407342495578,12.93487752118115 55.52383636385861,12.93485414710541 55.52383440570438,12.934617654824683 55.523814586663214,12.93462363716453 55.52379159287159,12.934373893839348 55.523767266014715,12.934262076501895 55.52419653040539,12.934160764140689 55.524585414273915)))`

and depending on geos-version, we get the following back out again. On 3.11.1 - we receive the expected geometry back: 
`MULTIPOLYGON (((12.932783211827351 55.52388199800951, 12.93245550269099 55.52385006659112, 12.932511159135071 55.52366627893948, 12.932034283234547 55.523792667409026, 12.932249636217353 55.52408517418492, 12.932380445341693 55.52409792424644, 12.932708140512728 55.52412986477694, 12.932783211827351 55.52388199800951)), ((12.934160764140689 55.524585414273915, 12.935069804474448 55.52439776732449, 12.935081366292575 55.52435334973056, 12.935114165594179 55.5243561507144, 12.935140137641318 55.52425637035675, 12.935184353995986 55.524086684745086, 12.935187805705446 55.52407342495578, 12.93487752118115 55.52383636385861, 12.93485414710541 55.52383440570438, 12.934617654824683 55.523814586663214, 12.93462363716453 55.52379159287159, 12.934373893839348 55.523767266014715, 12.934262076501895 55.52419653040539, 12.934160764140689 55.524585414273915)))`

but on 3.12.0 - it's suddenly converted into a geometry with Z, even though it's not specified and not provided: 
`MULTIPOLYGON Z (((12.932783211827351 55.52388199800951 0, 12.93245550269099 55.52385006659112 0, 12.932511159135071 55.52366627893948 0, 12.932034283234547 55.523792667409026 0, 12.932249636217353 55.52408517418492 0, 12.932380445341693 55.52409792424644 0, 12.932708140512728 55.52412986477694 0, 12.932783211827351 55.52388199800951 0)), ((12.934160764140689 55.524585414273915 0, 12.935069804474448 55.52439776732449 0, 12.935081366292575 55.52435334973056 0, 12.935114165594179 55.5243561507144 0, 12.935140137641318 55.52425637035675 0, 12.935184353995986 55.524086684745086 0, 12.935187805705446 55.52407342495578 0, 12.93487752118115 55.52383636385861 0, 12.93485414710541 55.52383440570438 0, 12.934617654824683 55.523814586663214 0, 12.93462363716453 55.52379159287159 0, 12.934373893839348 55.523767266014715 0, 12.934262076501895 55.52419653040539 0, 12.934160764140689 55.524585414273915 0)))`

**Comment by BuonOmo** [comment]
Thank you both for reporting this issue.

I think this is related to this change in geos:
- https://github.com/libgeos/geos/pull/908
- https://github.com/libgeos/geos/pull/915

This is quite unfortunate for us, seems like we'll have to do a conditional over geos version. I should have time to do that by next week. If anyone can do it beforehand that would be more than welcome!

**Comment by Tristramg** [comment]
Thank you a lot for your reactivity and for maintaining this gem!

**Comment by januszm** [comment]
Same just happened to me when I upgraded older app to GEOS 3.12 and Ruby 3.2

```ruby
> RGeo::Geographic.spherical_factory.point("2", "1")
=> #<RGeo::Geographic::SphericalPointImpl:0x7170 "POINT (2.0 1.0)">

> record.shape = RGeo::Geographic.spherical_factory.point("2", "1")
> record.save

> record.shape
=> #<RGeo::Geos::CAPIPointImpl:0x715c "POINT Z (2 1 0)">
> record.shape.to_s
=> "POINT Z (2 1 0)"
```

Would downgrading to GEOS 3.11 or 3.12 solve this issue too?

**Comment by keithdoggett** [comment]
@januszm once #364 is merged I'll release a version with these changes.
