### ISSUE TITLE
Area is not implemented / Wrong documentation

### ISSUE THREAD

**Issue by seuros** [rgeo/rgeo#40]
In the Section 3.5 of the rdoc : 

``` ruby
 p00 = factory.point(0, 0)
 p20 = factory.point(2, 0)
 p11 = factory.point(1, 1)
 p00.distance(p11)              # returns 1.41421356...
 line = factory.line(p00, p20)
 line.length                    # returns 2
 line.distance(p11)             # returns 1
 ring = factory.linear_ring([p00, p11, p20, p00])
 ring.length                    # returns 4.82842712...
 ring.distance(p11)             # returns 0
 poly = factory.polygon(ring)
 poly.area                      # returns 1
```

poly.area    is not implemented and raise : 

```
RGeo::Error::UnsupportedOperation: Method Surface#area not defined.
```

**Comment by viktorsmari** [comment]
What if I can call the `#area` method in IRB, but not inside Rails? 
What could then be the issue?

`area` works in IRB after `require 'rgeo'`
![2022-06-01_17-58-19](https://user-images.githubusercontent.com/1689020/171448404-f2e3cbee-6e2e-4647-9830-9f77f56cb4db.png)


![2022-06-01_17-59-19](https://user-images.githubusercontent.com/1689020/171448466-49a06c88-bcd8-4028-a541-65cc815fb9f2.png)

Running on Ubuntu 20, and installed the `libgeo*` mentioned in the readme.
