### ISSUE TITLE
Crash when using ffi-geos on mac

### ISSUE THREAD

**Issue by georgepalmer** [rgeo/rgeo#42]
Hi,

I've been using RGeo for several months on a project without any problems.  Recently we've had the need to make a direct ffi-geos call for a calculation so have added that gem to the project.  Unfortunately this results in rails crashing whenever I try and load a geometry object from the database.  The error is:

```ruby
dyld: lazy symbol binding failed: Symbol not found: _initGEOS_r
  Referenced from: /Users/george/.rvm/gems/ruby-1.9.3-p327@propertydetective/gems/rgeo-0.3.19/lib/rgeo/geos/geos_c_impl.bundle
  Expected in: flat namespace

dyld: Symbol not found: _initGEOS_r
  Referenced from: /Users/george/.rvm/gems/ruby-1.9.3-p327@propertydetective/gems/rgeo-0.3.19/lib/rgeo/geos/geos_c_impl.bundle
  Expected in: flat namespace

/Users/george/.rvm/gems/ruby-1.9.3-p327@propertydetective/gems/rgeo-0.3.19/lib/rgeo/geos/capi_factory.rb:120: [BUG] Segmentation fault
```

My ruby version is bang up to date (ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin12.2.0]) and I've tried this with the latest rgeo & ffi-geos too. So any ideas what's causing this? My initial thoughts are it's library related but then I'm confused as to why it would install in the first place if that were the case.   Just to be sure I wiped the gems and geos library and did a clean install but that didn't help.

I originally raised this against ffs-geos but after tracking it down I don't believe it ever uses that gem - although frustratingly it's presence in the bundle file does cause the crash.  That is if I remove it the gem then everything returns to normal.

George

**Comment by deivid-rodriguez** [comment]
@teeparham You think this is a bug in `rgeo` or this should be closed?

**Comment by teeparham** [comment]
Does this still happen with the latest release?

**Comment by deivid-rodriguez** [comment]
I don't know. But `RGeo::Geos.preferred_native_interface = :ffi` seems like an appropriate supported solution.
