### ISSUE TITLE
problems with union of geometry

### ISSUE THREAD

**Issue by fringd** [rgeo/rgeo#44]
When i query a pointset for intersection with 3 polygons (which should be adjacent and disjoint) i get the following

```
boxes.map {|box| Address.where { projected_latlon.op('&&', box) } }.map(&:size)
> [46, 18, 32]
```

ok... but when i do the following:

```
bigbox = boxes.inject &:union
Address.where { projected_latlon.op('&&', bigbox) }.size
> 117
```

here is my migration for the address

```
    add_column :addresses, :projected_latlon, :point, srid: 3785
    add_index :addresses, :projected_latlon, spatial: true
```

oh and my migration for the boxes column

```
    add_column :maponics_neighborhoods_1124_s12991, :projected_geom, :geometry, srid: 3785
```

here is an example box:

```
#<RGeo::Geos::CAPIPolygonImpl:0x57f8f64 "POLYGON ((-8574094.383298062 4694406.755065906, etc... 
```

everything is done in projected coordinates... I've painstakingly converted all of my data to projection thinking it would fix this problem, but whether i do the union in ruby with rgeo, or via squeel with st_union, i get the same terrible results

to make things even more fun... consider this third case

```
Address.where { projected_latlon.op('&&', boxes[0]) | projected_latlon.op('&&', boxes[1]) | projected_latlon.op('&&', boxes[2]) }.size
> 68
```

assuming these are disjoint i should get 96 for SURE... :(

if i use & (and) instead of | (or) i get 0 results...

clues?

:(

**Comment by BuonOmo** [comment]
@fringd We're currently working on adding more elements to the documentation. If you now have examples we'd be glad you share those. 

Otherwise I'll close this issue since it is stale since 2013.
