### ISSUE TITLE
Int to Double with Jruby?

### ISSUE THREAD

**Issue by ldonnet** [rgeo/rgeo#45]
Hi,

I want to use rgeo to manipulate spatial object with jruby (1.7.1) and ffi-geos. I try this : 

```
rgeo_factory = RGeo::Geos.factory(:srid => 4326, :wkt_parser => {:support_ewkt => true})
puts rgeo_factory.point(2, 0).inspect
puts rgeo_factory.point(2.0, 0).inspect
```

And the result is : 

```
<RGeo::Geos::FFIPointImpl:0x7d0 "POINT (1.0E-323 0.0)">
<RGeo::Geos::FFIPointImpl:0x7d0 "POINT (2.0 0.0)">
```

I suppose there is a problem to convert int in double. I havn't this bug with ruby. Do you know is it a problem with ffi or ffi-geos?

Thanks for your help

**Comment by keithdoggett** [comment]
I'm going to close this since it's very old and may have been solved in new versions of JRuby, ffi,  or ffi-geos. If it is still an issue, please open up a new issue.
