### ISSUE TITLE
20 km shift with SRID 32188

### ISSUE THREAD

**Issue by kaligrafy** [rgeo/rgeo#48]
Hi!

I tried to convert a lat/lon geographic geometry to MTM8 (SRID 32188) and I get a 20km shift (almost 20000 meters too high) for the y, but the x is correct.

If I use directly the postgis function ST_Transform, there is no shift.

Here is the rgeo command I use to transform (the one that shifts 20km):
RGeo::Feature.cast(geometry_attribute, :factory => RGeo::Cartesian.factory(:srs_database => RGeo::CoordSys::SRSDatabase::ActiveRecordTable.new, :srid => 32188), :project => true)

Thanks for any cue!

**Comment by kaligrafy** [comment]
lat and lon are reversed...

**Comment by keithdoggett** [comment]
I tried @ddd1600's solution (while flipping lat/lon) and it worked. This issue is very old and a lot has changed since then, so I'm going to close but if this still isnt' working, please open a new issue.
