### ISSUE TITLE
Problems with spherical_factory and WKT polygon with repeated vertexes

### ISSUE THREAD

**Issue by gekorob** [rgeo/rgeo#49]
Hi all,
  I've a problem with the code below:

```
  wkt = "POLYGON((-53.36 -65.98, -49.49 -67.09, -45.27 -68.10, -45.27 -68.10, -46.09 -68.62, -53.36 -65.98))"
  factory = RGeo::Geographic.spherical_factory(:srid => 4326)
  feature = factory.parse_wkt(wkt)
  feature.should_not be nil     #FAIL
```

This test fails, because in the polygon (which I extracted from third party source) there are to identical vertexes (perhaps this is what I understood after several trials in a file with thousands of polygons).
Eliminating one of the two vertexes, everything works well

```
  wkt = "POLYGON((-53.36 -65.98, -49.49 -67.09, -45.27 -68.10, -46.09 -68.62, -53.36 -65.98))"
  factory = RGeo::Geographic.spherical_factory(:srid => 4326)
  feature = factory.parse_wkt(wkt)
  feature.should_not be nil     #PASSED
```

What I'm missing? Is this the normal behaviour?
Thanks in advance,
  best regards
    Roberto

**Comment by fxthomas** [comment]
After discovering the difference between Geographic and Cartesian factories, I switched one of my models to use `RGeo::Geographic.spherical_factory` to be able to compute distances without having to change reference systems.

Suddenly, polygons with duplicate nodes were converted to `nil`, which was quite unexpected :

    > wkt = "POLYGON((-53.36 -65.98, -49.49 -67.09, -45.27 -68.10, -45.27 -68.10, -46.09 -68.62, -53.36 -65.98))"
    > RGeo::Cartesian.factory.parse_wkt wkt
    #<RGeo::Geos::CAPI...>
    > RGeo::Geographic.spherical_factory.parse_wkt wkt
    nil

_(Using RGeo 0.3.20)_

**Comment by keithdoggett** [comment]
I'm closing this since #74 seems to fix this issue.
