### ISSUE TITLE
GEOS is supported in irb but unavailable in rake

### ISSUE THREAD

**Issue by serene** [rgeo/rgeo#52]
Below is my rake task code. RGeo::Geos.supported? returns false. When I run the same code in irb, I don't receive the same error, and the shapefile loads just fine.

namespace :read_shp do
  task :read_shapefile => :environment do
    puts RGeo::Geos.supported?

    RGeo::Shapefile::Reader.open("myshapefile.shp") do |file|
      puts "File contains #{file.num_records} records."
      file.each do |record|
        puts "Record number #{record.index}:"
        puts "  Geometry: #{record.geometry.as_text}"
        puts "  Attributes: #{record.attributes.inspect}"
      end
      file.rewind
      record = file.next
      puts "First record geometry was: #{record.geometry.as_text}"
    end
  end
end

**Comment by guizmaii** [comment]
I have the same problem.
My local gems are the followings : 

*** LOCAL GEMS ***

rgeo (0.3.20)
rgeo-activerecord (0.4.6)

I'm not using ```rgeo-shapefile``` so I can't set the ```:assume_inner_follows_outer``` to true.

In irb, ```RGeo::Geos.supported?```, ```RGeo::Geos.capi_supported?``` and ```RGeo::Geos.ffi_supported?``` are all ```true```.
But in my rake task, they are all ```false```

Any solution ?

**Comment by deivid-rodriguez** [comment]
This is a setup issue and a general problem with gems containing C-extensions. Besides, we're already pointing out that you need `devel` packages in the README.

So I guess we can close this.
