### ISSUE TITLE
unproject fails with multiple ruby processes (e.g. in production)---need to support new rails 4 eager load API

### ISSUE THREAD

**Issue by kashif** [rgeo/rgeo#54]
If I create my class as:

``` ruby
class Location < ActiveRecord::Base
  GEOM_FACTORY ||= RGeo::Geographic.projected_factory(projection_srid: 21781, srid: 4326, projection_proj4: '+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs', has_z_coordinate: false)

  set_rgeo_factory_for_column(:coords, GEOM_FACTORY.projection_factory)
  attr_reader :latlng

  ...

  def latlng
    GEOM_FACTORY.unproject(coords)
  end
end
```

The `latlng` method fails if it gets called from a worker process in a production environment with the error:

```
RGeo::Error::InvalidGeometry (You can unproject only features that are in the projected coordinate space.):
  app/models/location.rb:15:in `latlng'
...
```

The reason seems to be the following line: 
https://github.com/dazuma/rgeo/blob/master/lib/rgeo/geographic/factory.rb#L304 where `@projector` is `nil`.

BTW:

```
$ uname -a
Linux box 3.2.0-23-virtual #36-Ubuntu SMP Tue Apr 10 22:29:03 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

$ ruby -v
ruby 1.9.3p429 (2013-05-15) [x86_64-linux] Brightbox

$ bundle exec rails c production
Loading production environment (Rails 4.0.0.rc2)
irb(main):004:0> RGeo::Geos.supported?
=> true
irb(main):005:0> RGeo::CoordSys::Proj4.supported?
=> true
```

I am using Apache with passenger and the issue goes away when I set the `PassengerSpawnMethod` to `conservative` (`direct`). See here: http://www.modrails.com/documentation/Users%20guide%20Apache.html#PassengerSpawnMethod

**Comment by harmdewit** [comment]
Thanks @mswezey! I updated to rails 4.2 today and i ran into this issue again. I previously managed to fix this by configuring eager_load paths, e.g. `config.eager_load_paths -= ["#{config.root}/app/models", "#{config.root}/app/models/concerns"]`. However after the update this config didn't work anymore, but your solution did

**Comment by BuonOmo** [comment]
I'm closing this issue since it's been stale 5 years now. Please open another one if this bug come again in a new rails version.
