### ISSUE TITLE
downgrade ZMPolygonImpl to simply 2D PolygonImpl

### ISSUE THREAD

**Issue by ddd1600** [rgeo/rgeo#58]
Some of my methodologies are failing because of a bunch of superfluous M & Z coordinates in my shape file data. How do I downgrade these polygons to simply X,Y objects?

**Comment by keithdoggett** [comment]
I'm going to close this since its stale but one solution could be to use a factory that accepts m and z coordinates to parse the shapefile and then convert them by iterating through the points in each geometry and just taking the x and y coordinates.
