### ISSUE TITLE
RGeo doesn't recognize GEOS on the Mac OS built-in ruby

### ISSUE THREAD

**Issue by dazuma** [rgeo/rgeo#6]
Received and verified a report that, when installing rgeo on the built-in ruby on Mac OS X 10.6 (Snow Leopard), GEOS doesn't get recognized even if it is installed.

**Comment by no17436** [comment]
@robkooper still helpful. Thanks!

**Comment by barrettclark** [comment]
Thanks @robkooper. Still helpful with Postgres.app on PG 9.4 (just changed 9.3 to 9.4):

    ARCHFLAGS="-arch x86_64" gem install rgeo -V -- \
    --with-geos-include=/Applications/Postgres.app/Contents/Versions/9.4/include \
    --with-geos-lib=/Applications/Postgres.app/Contents/Versions/9.4/lib \
    --with-proj-include=/Applications/Postgres.app/Contents/Versions/9.4/include \
    --with-proj-lib=/Applications/Postgres.app/Contents/Versions/9.4/lib

**Comment by deivid-rodriguez** [comment]
This should work since the library path is now auto detected on installation.

**Comment by denispeplin** [comment]
In some old project, where `rgeo` 0.3.20 is being used, I had to run `sudo apt-get install libgeos-dev` and to reinstall both `rgeo` and `ffi-geos` to solve the application mysterious crash on start. Thanks to this thread which revealed some details!

**Comment by millisami** [comment]
I've a different case. In macOS mojave, in irb it is supported i.e. `RGeo::Geos.supported?` returns `true` but using `bundle exec rails c`, it returns `false`. Why is this different with bundler?

**Comment by jrreyes29** [comment]
> I've a different case. In macOS mojave, in irb it is supported i.e. `RGeo::Geos.supported?` returns `true` but using `bundle exec rails c`, it returns `false`. Why is this different with bundler?

For me happend the same with irb I got true and with rails console I got false, why???

**Comment by humphreyja** [comment]
> I've a different case. In macOS mojave, in irb it is supported i.e. `RGeo::Geos.supported?` returns `true` but using `bundle exec rails c`, it returns `false`. Why is this different with bundler?

This one got me stuck for a little bit. Showed up after switching branches. Go into your activity monitor and kill any running ruby processes. Spring is probably causing some issues with memory here.
