### ISSUE TITLE
rgeo does not recognize Ubuntu 13.10's GEOS

### ISSUE THREAD

**Issue by JasonBarnabe** [rgeo/rgeo#60]
I installed libgeos-dev from Synaptic package manager. This installs to /usr/lib/libgeos-3.3.3.so, which rgeo apparently can't find. After running

```bash
sudo ln -s /usr/lib/libgeos-3.3.3.so /usr/lib/libgeos.so
```
and removing and reinstalling geos, things work.

Is this rgeo's problem, or is it GEOS's, or Ubuntu's, or mine? I don't know.

**Comment by tneems** [comment]
I've also run into this on Ubuntu 14.04. The symlink fixed it for me too.

**Comment by deivid-rodriguez** [comment]
This should be fixed now.
