### ISSUE TITLE
not compatible with ruby 2.1?

### ISSUE THREAD

**Issue by kaligrafy** [rgeo/rgeo#63]
It seems when using ruby 2.1, rgeo can't work with geos and proj4 (it says it did not find them, yet they are fine and working when installing with ruby 2.0.0)

I can confirm everything works fine when doing this: rvm use 2.0.0
but when doing this: rvm use 2.1.0, I get:
RGeo::Geos.supported?  => false
RGeo::CoordSys::Proj4.supported? => false
and I did reinstall everything on both ruby versions...

**Comment by rpallai** [comment]
I also have issues on Debian Jessie;

>\# gem install -V rgeo
[...]
Building native extensions.  This could take a while...
/usr/bin/ruby2.1 extconf.rb
checking for geos_c.h... yes
checking for GEOSSetSRID_r() in geos_c.h... yes
checking for GEOSPreparedContains_r() in geos_c.h... yes
checking for GEOSPreparedDisjoint_r() in geos_c.h... yes
checking for GEOSWKTWriter_setOutputDimension_r() in geos_c.h... yes
checking for rb_memhash() in ruby.h... yes
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
compiling point.c
compiling factory.c
compiling geometry.c
compiling line_string.c
compiling main.c
compiling polygon.c
compiling geometry_collection.c
linking shared-object rgeo/geos/geos_c_impl.so
make "DESTDIR=" install
/usr/bin/install -c -m 0755 geos_c_impl.so ./.gem.20150309-19656-1hy2rdk/rgeo/geos
installing default geos_c_impl libraries

>/usr/bin/ruby2.1 extconf.rb
checking for proj_api.h... yes
checking for pj_init_plus() in proj_api.h... yes
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
compiling main.c
linking shared-object rgeo/coord_sys/proj4_c_impl.so
make "DESTDIR=" install
/usr/bin/install -c -m 0755 proj4_c_impl.so ./.gem.20150309-19656-42q14l/rgeo/coord_sys
installing default proj4_c_impl libraries

>Successfully installed rgeo-0.3.20
Parsing documentation for rgeo-0.3.20
Parsing sources...
100% [86/86]  lib/rgeo/yaml.rb                                                  
Done installing documentation for rgeo after 3 seconds
1 gem installed

>$ irb -rrgeo
\> RGeo::Geos.capi_supported?
=> false
\> RGeo::CoordSys::Proj4.supported?
=> false
\> RUBY_VERSION
=> "2.1.5"

>$ irb
\> require 'rgeo/geos/geos_c_impl'
=> true
\> require 'rgeo/geos/geos_c_impl'
=> false

On my old box where rgeo works with geos/proj4:
>$ irb
\> require 'rgeo/geos/geos_c_impl'
NameError: uninitialized constant RGeo::Feature::Geometry
\> RUBY_VERSION
=> "1.9.3"

**Comment by dmitry** [comment]
What libgeos do you have?

**Comment by rpallai** [comment]
@dmitry As I wrote in the footer I have resolved this issue. BTW libgeos is 3.4.2. thx

**Comment by deivid-rodriguez** [comment]
This can be closed! :smile:
