### ISSUE TITLE
rgeo-0.3.20 failure with proj on mac  

### ISSUE THREAD

**Issue by mflorisson** [rgeo/rgeo#64]
During code execution, rgeo 0.3.20 fails to link to proj ("_pj_init_plus").
- I get this error message:
  <pre>
  dyld: lazy symbol binding failed: Symbol not found: _pj_init_plus
  Referenced from: /Users/marc/.rvm/gems/ruby-1.9.3-head/gems/rgeo-0.3.20/lib/rgeo/coord_sys/proj4_c_impl.bundle
  Expected in: flat namespace
  </pre>

I'm working on Mac environment (Mountain Lion).
I'm using ruby 1.9.3p455 (2013-07-17) [x86_64-darwin12.4.0].
- I've installed proj with brew:
  <pre>
  brew info proj
  proj: stable 4.8.0
  http://trac.osgeo.org/proj/
  /usr/local/Cellar/proj/4.8.0 (47 files, 5,7M) *
  Built from source
  From: https://github.com/Homebrew/homebrew/commits/master/Library/Formula/proj.rb
  </pre>

Could some one help me ?

**Comment by teeparham** [comment]
Proj4 has been extracted to a separate gem, `rgeo-proj4`. Please try the latest version of rgeo and re-open this issue in https://github.com/rgeo/rgeo-proj4 if it is still a problem. Thanks.
