### ISSUE TITLE
RGeo : latitude and longitude methods for RGeo::Feature::Point?

### ISSUE THREAD

**Issue by ldonnet** [rgeo/rgeo#66]
Perhaps, I miss something but it could be helpful to have latitude (lat) and longitude (lon) methods in RGeo::Feature::Point? It could be just an alias for x and y methods. 

Thanks for all your great work with rgeo and postgis!

**Comment by allthesignals** [comment]
x and y don't seem aliased for RGeo::Geos::CAPIPointImpl - is this intentional? Thank you.

**Comment by dazuma** [comment]
Yes, it is intentional. As others have mentioned above, lat and lon make sense only in a geographic coordinate system. Geos in particular works in a flat coordinate system (such as a projection), so having lat and lon methods would be confusing and invite users to do the wrong thing.
