### ISSUE TITLE
Error::InvalidGeometry, 'You can unproject only features that are in the projected coordinate space.'

### ISSUE THREAD

**Issue by abatko** [rgeo/rgeo#72]
I ran into this error for the first time today. My experience is different than what I think is described in [issue 54](https://github.com/rgeo/rgeo/issues/54), as I am running in **development** mode and have `config.eager_load = false`. Furthermore, I am _unable_ to consistently reproduce the error - it only happens **sometimes**. When the error does happen, I can still successfully issue the call manually via `rails console` (which is always running - i.e. I don't just fire it up when something goes wrong):

`::Model::RGEO_FACTORY.unproject(Model.find(61).geopoint).lat`

Incidentally, I have been _unable_ to reproduce this error in my **test** environment, where `config.eager_load` is also set to `false`.

**db/schema.rb:**
`t.spatial  "geopoint",               limit: {:srid=>3785, :type=>"point"}`

**model.rb:**

```
RGEO_FACTORY = RGeo::Geographic.simple_mercator_factory
set_rgeo_factory_for_column(:geopoint, RGEO_FACTORY.projection_factory)

def geopoint_geographic
    RGEO_FACTORY.unproject(geopoint)
end
```

The exception is found in `rgeo`'s [unproject method](https://github.com/rgeo/rgeo/blob/f9be805a4973c7aef8172b11d784db62d37d1278/lib/rgeo/geographic/factory.rb#L305):

```
      def unproject(geometry_)
        return nil unless geometry_
        unless @projector && @projector.projection_factory == geometry_.factory
          raise Error::InvalidGeometry, 'You can unproject only features that are in the projected coordinate space.'
        end
        @projector.unproject(geometry_)
      end
```

I am running on the following versions:
- `ruby 2.0.0p481`
- `rails 4.0.5`
- `PostgreSQL 9.3.4 on x86_64-apple-darwin13.1.0, compiled by Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn), 64-bit`
- `POSTGIS="2.1.1 r12113" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.0, released 2013/04/24" LIBXML="2.9.1" LIBJSON="UNKNOWN" (core procs from "2.1.0 r11822" need upgrade) RASTER (raster procs from "2.1.0 r11822" need upgrade)`
- `rgeo (0.3.20)`
- `rgeo-activerecord (1.0.0)`

This is a really strange one, because of its inconsistent nature. Thoughts?

**Comment by keithdoggett** [comment]
I'm going to close this as stale since the way factories are assigned via `activerecord-postgis-adapter` has changed a lot since this.
