### ISSUE TITLE
RGeo point returning nil only on Heroku

### ISSUE THREAD

**Issue by TimKJones** [rgeo/rgeo#78]
I'm using activerecord-postgis-adapter to save (latitude, longitude) values as `POINT`s.  Points are saved using the following syntax: `POINT( lng lat)`.  My model, `Foo`, has an attribute `spot`, where the `POINT` is saved.  When deployed to Heroku, `spot` is always nil after creating a new `Foo`.  However, it works as expected in the following situations:
- Locally with development database (both in production and development environments)
- Locally while connected to production database
- In the rails console inside Heroku

activerecord-postgis-adapter is the same version both locally and on Heroku (2.2.0).  Does anyone have any ideas as to what could be different in the Heroku production environment (that doesn't surface in the console) that might be causing this?

`Foo` uses the `spherical_factory` by default:

`self.rgeo_factory_generator = RGeo::Geos.factory_generator`
`set_rgeo_factory_for_column(spot, RGeo::Geographic.spherical_factory(:srid => 4326))`

**Comment by rossettistone** [comment]
Heroku takes a little extra setup to get postgis working. I've struggled with this a fair bit, and found the solutions out there to be somewhat unreliable, but here are some starter points that might address this issue:
https://devcenter.heroku.com/articles/postgis (Heroku's official article on the matter)
https://github.com/cyberdelia/heroku-geo-buildpack (also linked to from the Heroku article)

I realize this issue is pretty stale, but maybe these resources will help someone else...

**Comment by CarlosLCervantes** [comment]
I just spent 6 hours getting this to work. I upgraded Rails from 4.1 to 4.2 which required upgrading Active Record -> Active Record PostGIS -> RGeo. Somehow this broke our existing Rgeo to Geos linking. I have three pieces of advice for anyone who might get stuck with this not working.

1. First and most obvious is to use the heroku geo buildpack mentioned above. So you can automatically pull down the GEOS lib when spinning up a dyno.

2. Make sure that the geo buildpack runs before the ruby buildpack. Basically it needs to run before the app starts bundling. The sooner in the list of buildpacks the better (the sooner the build pack runs the better).

3. Purge the repo cache using this heroku plugin https://github.com/heroku/heroku-repo specially the command `heroku repo:purge_cache -a appname`.

Good luck.
