### ISSUE TITLE
Feature.cast from geographic to geometry sets lat/lon as x/y but doesn't project

### ISSUE THREAD

**Issue by ericcj** [rgeo/rgeo#81]
while using activerecord-postgis-adapter i noticed that if i have a column with a projected factory but assign a geographic point to it, the setter doesn't raise.  instead it casts that point into the projected space (it becomes an RGeo::Cartesian::PointImpl with the projected srid) but instead of projecting the lat/lon it just treats them as x/y which results in junk data.  

digging into it, SpatialColumn#convert_to_geometry is calling RGeo::Feature.cast (without passing the "project" option but that doesn't seem to help anyways).  is this the desired behavior of that method?  it seems like casting from one srid to another should require projection or just raise if it's incapable, but never produce a point by just copying coordinates from a different projection and then claiming they are in the srid you casted to.  e.g., putting the following test into tc_types.rb fails:

```
      def test_cast
        spherical_point = RGeo::Geographic.spherical_factory.point(-127, 39)
        cast_point = RGeo::Feature.cast(spherical_point, factory: RGeo::Geographic.simple_mercator_factory.projection_factory, project: true)
        assert_not_equal spherical_point.longitude, cast_point.x
      end
```

**Comment by schmijos** [comment]
Your test works for me. But I found out something interesting. If I put into your code the following

    puts cast_point.srid

It writes `3857` as a result. Shouldn't it be `3785`? At least it's documented like that in my gem from rubygems: `gems/2.2.0/gems/rgeo-0.3.20/lib/rgeo/geographic/interface.rb:208`.

**Comment by keithdoggett** [comment]
Closing since this is an issue with the proj4 setup. Though I will likely add a warning if the proj4 strings are nil for either factory so it doesn't fail unexpectedly.
