### ISSUE TITLE
GEOS not supported in Ubuntu 12.4

### ISSUE THREAD

**Issue by pankas87** [rgeo/rgeo#86]
I'm using RVM with ruby-2.0.0-p576

My libgeos package is installed in the /usr/lib folder, when I install RGeo I use the command

    gem install rgeo -- --with-geos-dir=/usr/lib

to install the Rgeo gem.

When I go to my Rails project and use the Rails console with

    bundle exec rails c

and try

    RGeo::Geos.supported?

it returns false

Is there anything else I need to do? Am I missing something?

The first time I installed RGeo I didn't use the *--with-geos-dir* may be it has something to do, I don't know

**Comment by figuedmundo** [comment]
Maybe you could follow this https://github.com/rgeo/rgeo/issues/26

Once I had the same problem maybe is the same that the one you have now

*figuedmundo <https://github.com/figuedmundo> *commented on May 31, 2012
<https://github.com/rgeo/rgeo/issues/26#issuecomment-6039983>

I installed the libgeos-dev and reinstalled the rgeo gem and it works,, Tnks

Regards,

2015-01-29 15:40 GMT-04:00 Leonardo Graterol <notifications@github.com>:

**Comment by pankas87** [comment]
@figuedmundo I tried that, but it still doesn't work.

It's odd because when I install the gem using the --verbose option GEOS is correctly linked, apparently, here's a gist with the output

https://gist.github.com/pankas87/71576571aa64e677e42c

**Comment by pankas87** [comment]
Ok... I got it to work, but only under irb.

When I try 

    RGeo::Geos.supported?

I still get false

**Comment by pankas87** [comment]
It is working, I had to do the following.

    #remove previous rgeo installation
    gem uninstall rgeo
        
    #install GEOS packages
    sudo apt-get install libgeos-dev
    sudo apt-get install libgeos-3.3.8

    #install proj package, I don't actually but not sure if it wasn't working because of this
    sudo apt-get install proj
    
    #clone the repo of the rails project in other location, Rails apparently insisted on using the old, unlinked to GEOS, version of the gem
    
    #And the reinstall the project's gems
    bundle install

Worked like a charm

**Comment by abersh** [comment]
configure: error: Topology requires GEOS version >= 3.3.2. Use --without-topology or install a newer GEOS.

**Comment by Ume1931** [comment]
bundle install --force did the trick.
Basically after installing geos packages, you need to reinstall your rgeo gem.
But when you are using rvm "gem uninstall rgeo" wont work.
You need to explicitly reinstall all gems using above command.

**Comment by stulentsev** [comment]
> I installed the `libgeos-dev` and reinstalled the rgeo gem and it works

This worked for me on ubuntu 18.04 (although I installed also `libproj-dev`, just in case).
