### ISSUE TITLE
RGeo::Geos buffer not working as it should

### ISSUE THREAD

**Issue by HenrYxZ** [rgeo/rgeo#91]
I have a circle overlay from Google Maps. The longitude is -70.60449600219727 and latitude -33.43353200017386. The radius is 1233.073592216796. 
It worked fine using

``` ruby
factory = RGeo::Cartesian.factory(
  srid: 4326, buffer_resolution: 8
)
circle = factory.point(lon, lat).buffer(radius)
```

But then I installed libgeos-dev and libproj-dev to use the difference function. And after that
circle would give something like this `RGeo::Geos::CAPIPolygonImpl:0x3fc8980 "POLYGON ((1162.3955039978027 -33.43353200017386, 1138.703754734986 -273.97989904605976, 1068.5389675842196 -505.28220410632906, 954.5975359668414 -718.4516293133428, 801.2581652008166 -905.2961932031861, 614.4136013109733 -1058.6355639692115, 401.2441761039597 -1172.5769955865899, 169.94187104369058 -1242.7417827373567, -70.60449600219528 -1266.433532000174, -311.1508630480812 -1242.7417827373574, -542.4531681083506 -1172.5769955865915, -755.6225933153647 -1058.6355639692135, -942.4671572052084 -905.2961932031889, -1095.8065279712337 -718.451629313346, -1209.7479595886125 -505.2822041063327, -1279.9127467393796 -273.9798990460636, -1303.6044960021973 -33.43353200017785, -1279.9127467393812 207.1128350457081, -1209.7479595886157 438.4151401059776, -1095.8065279712382 651.5845653129917, -942.467157205214 838.4291292028356, -755.6225933153713 991.7684999688614, -542.4531681083577 1105.7099315862406, -311.1508630480882 1175.8747187370082, -70.60449600220187 1199.566467999826, 169.9418710436846 1175.87471873701, 401.24417610395466 1105.7099315862442, 614.413601310969 991.7684999688664, 801.2581652008133 838.4291292028418, 954.5975359668391 651.5845653129984, 1068.5389675842182 438.4151401059847, 1138.7037547349853 207.112835045715, 1162.3955039978027 -33.43353200017386))"`

Which is like all the world. How can I fix this?

**Comment by HenrYxZ** [comment]
I think maybe Geos is using only geometry and not geography. So to get the geometry I had to do this:

```ruby
factory = RGeo::Geographic.spherical_factory(srid: 4326, buffer_resolution: 8)
geography = factory.point(lon, lat).buffer(radius)
circle = RGeo::Geos.factory(srid: 4326).parse_wkt(geography.to_s)
```

Then I was able to do `circle.intersection(geom)` where geom is a Geos geometry.

**Comment by keithdoggett** [comment]
The unit for radius, in this case, is degrees, not meters so you'd have to find some way to convert between meters and degrees for the Geos factory. It works with the Geographic factory because that uses meters as units for distance.

I'm going to close since this is the expected behavior (albiet EPSG:4326 can be somewhat confusing).

**Comment by HenrYxZ** [comment]
thanks!
